### ISSUE TITLE
Cryptographie douteuse

### ISSUE THREAD

**Issue by jvoisin** [broncowdd/BoZoN#1]
Le fichier auto_restrict.php est inquiétant.
1. Il y a de la crypto maison avec du md5 et du xor, au lieu d'utiliser des [primitives connues](http://www.php.net/manual/en/mcrypt.ciphers.php) qui fournissent de vraies propriétés cryptographiques.
2. La variable $_SESSION['id_user'] (le token de session) peut être retrouvée par l'utilisateur, et n'a rien de random. Une implémentation correcte est expliquée [ici](http://stackoverflow.com/questions/5009685/encoding-cookies-so-they-cannot-be-spoofed-or-read-etc/5009903#5009903).
3. Rien contre le CSRF
4. Pourquoi le nom du cookie est un hash du User-Agent ?!
5. Les tests d'égalité entre la valeurs stockées du mot de passe et du login sont fait avec un "==", ce qui permet de [bypass certaines valeurs](http://phpsadness.com/sad/47).

**Comment by broncowdd** [comment]
Update in auto_restrict
