### ISSUE TITLE
indexation par les moteurs de recherche ? 

### ISSUE THREAD

**Issue by cborne** [broncowdd/BoZoN#10]
une page "publique" peut elle se retrouver indexée par les moteurs de recherche ? As tu fais le nécessaire concrètement.

**Comment by broncowdd** [comment]
A priori pas de raison d'avoir une page répertoriée, mais ça mérite en effet de se pencher dessus... un robot.txt et une balise méta suffiront.
Le problème ne se poserait éventuellement que pour un lien de partage d'un dossier éventuellement diffusé sur un blog...

**Comment by cborne** [comment]
ce qui nous amène à éventuellement un bouton régénérer les liens au cas 
où le lien est devenu public ?

**Comment by broncowdd** [comment]
oui, ce serait une bonne idée (et facile à réaliser).
option 1: un bouton (encore) mais ça commence à faire bcp ^^
option 2: un formulaire dans lequel on colle le lien à renouveler et qui le régénère... (sur la future page de config, peut-être...

J'avais pensé aussi à faire une option rendant un lien temporaire: un burn it after reading permettant d'accéder au fichier une seule fois.

**Comment by cborne** [comment]
l'augmentation du nombre de boutons prouve bien la nécessité d'une page 
de configuration

**Comment by broncowdd** [comment]
la difficulté réside dans le fait que la page de config ne peut pas proposer une option qui nécessite de lister les fichiers, ce qui serait redondant.
Dans le cas de la gestion des liens de partage, j'imagine bien un mode spécifique de listage des fichiers qui remplacerait les boutons habituels par de nouveaux permettant la gestion des droits et modalités d'accès ...

J'y réfléchis sérieusement pour une version ultérieure: je vais déjà essayer de stabiliser cette version 1.4 avant d'implémenter des choses plus complexes.

**Comment by cborne** [comment]
je pense qu'il faudra rapidement arriver au bouton "secours" sans 
forcément tomber dans le paramétrage fin par répertoire ou par fichier. 
J'entends par là que si on part du principe que Bozon reste dans un 
cadre restreint, renvoyer au pire un lien à une dizaine de personnes 
n'est pas la fatalité.

**Comment by broncowdd** [comment]
#11
