### ISSUE TITLE
upload fichiers "exotiques"

### ISSUE THREAD

**Issue by fidoboulettes** [broncowdd/BoZoN#100]
Bonjour,

Je ne sais pas si c'est le lieu pour poster ce genre de chose mais voici:
grâce à l'ami Cyrille que je suis depuis un moment, je suis "tombé" sur ton service que je me suis empressé d'installer sur mon serveur.... Vraiment très chouette, simple à installer et léger... Et français en plus ma brave dame!!!!
Voulant partager avec tous les utilisateurs un fichier de mots de passe type keepass, je me suis vu refusé par bozon l'upload dudit fichier (xxx.kdbx) ... pour contourner le problème, j'ai du créer un fichier zip que j'ai transféré et re-décompressé... du coup je me demande quels sont les types de fichiers acceptés par bozon?

Question subsidiaire: Quel logiciel "inter OS si possible" puis je utiliser pour faire une synchro entre tous mes "appareils"?

Merci des réponses et du travail de tout le monde.

**Comment by broncowdd** [comment]
Merci pour les compliments qui font toujours plaisir ^_^
C'est un problème déjà rencontré qui vient de la détection du type mime du fichier: en cas de fichier non reconnu, il est interdit par défaut.
pour changer ça, il suffit, en attendant le correctif de la prochaine version, de modifier le fichier core/auto_dropzone.php à la ligne 295
```
function is_allowed(filemime){
            var r='<?php echo $auto_dropzone['forbidden_filetypes']; ?>';
            var allow=<?php echo $auto_dropzone['allow_unknown_filetypes']; ?>;
            m=filetype(filemime);
            if (m==''){return false;} // remplacer false par true !
            if(r.indexOf(m)==-1){return true;}
            else{return false;}
        }
```

**Comment by fidoboulettes** [comment]
Bon bah j'y arrive pô....mais comme je suis une vraie buse en linux et serveur... cela vient de moi.... merci en tout cas de ton aide et je crois que je vais attendre  ton correctif....
sinon, une idée pour faire des synchro à la owncloud mais que c'est pas du owncloud?

merci encore pour ton travail

**Comment by broncowdd** [comment]
Dans cette version 2.4 build 4, il y a une variable de configuration ;-)
