### ISSUE TITLE
Migration 2.3 vers 2.4

### ISSUE THREAD

**Issue by fpp-gh** [broncowdd/BoZoN#104]
Premiers retours à chaud sur le passage d'une 2.3 installée à la 2.4 :+1: 

1. les progrès de la nouvelle interface sont vertigineux :-)

Mais :

2. la page d'accueil affiche toujours "BoZon 2.4 beta", c'est normal ? :-)

3. la procédure de migration indiquée par Cyrille en bas de page :
http://bozon.pw/fr/static1/installer
... est exacte **seulement** si le fichier config.php n'a pas été modifié lors de l'installation initiale :-)
J'avais renommé le dossier "uploads" de la 2.3 en autre chose (puis oublié...)
Du coup ma 2.4 était "vide"...
J'ai renommé après coup uploads de la même façon, et tout est revenu (en apparence au moins)

4. Sauf que j'ai un dossier "images" qui ne marche plus bien :
Il affiche bien les vignettes (en mode liste comme en galerie)
... mais pas les images elles-mêmes : écran noir avec message
"L'image http://... ne peut être affichée car elle contient des erreurs"

5. pensant que c'était peut-être lié au point 3, j'ai tout supprimé, recréé le dossier et retéléchargé les images de tests : c'est pareil...

6. nouveauté au passage : une des images était en PNG, elle ne passe plus... j'ai dû la convertir en JPG pour pouvoir l'uploader... mais s'affiche toujours pas

7. dans le log nginx j'ai plein de nouvelles erreurs, du style :
 [error] 28713#0: *59862 FastCGI sent in stderr: "PHP message: PHP Warning:  imagecreatefromjpeg(): 'storage/fpp/img/bm160320.jpg' is not a valid JPEG file in /usr/share/nginx/www/bz/core/auto_thumb.php on line 65" while reading response header from upstream
 [error] 28713#0: *59888 FastCGI sent in stderr: "PHP message: PHP Warning:  mime_content_type(thumbs/storage/fpp/img/bm160320_THUMB_64x64.jpg): failed to open stream: No such file or directory in /usr/share/nginx/www/bz/core/core.php on line 667
PHP message: PHP Warning:  filesize(): stat failed for thumbs/storage/fpp/img/bm160320_THUMB_64x64.jpg in /usr/share/nginx/www/bz/core/commands_GET_vars.php on line 16
PHP message: PHP Warning:  readfile(thumbs/storage/fpp/img/bm160320_THUMB_64x64.jpg): failed to open stream: No such file or directory in /usr/share/nginx/www/bz/core/commands_GET_vars.php on line 17" while reading response header from upstream
etc...

8. avant l'étape 5, j'avais récupéré les images et vignettes sur mon PC pour vérifier leur état :
les images sont toutes OK (y compris le PNG)
les vignettes aussi, sauf que IrfanView se plaint que ce sont des PNG avec l'extension JPG ?

Bon c'est tout pour le moment :-)

**Comment by fpp-gh** [comment]
8. (post scriptum) :
Pour en avoir le coeur net, j'ai supprimé toute l'arborescence sur le serveur et dézippé un bozon-master neuf, récréé les dossiers de tests, remonté les images de test, pareil...

**Comment by broncowdd** [comment]
Salut et merci pour la remontée de bug ^^
Tu as renommé le dossier storage/ en upload/ c'est ça ?
Du coup, les chemins dans la base des id ne devaient plus être corrects... pas plus que le chemin vers les thumbs qu'il a sans doute recréé. Il aurait mieux valu éditer le config.php, se déconnecter puis se reconnecter, ça aurait sans doute marché ^^

Ce qui est étrange, c'est que le problème de format d'image persiste même en cas de réinstall... sauf si il y a une erreur de php qui en altère les données: en effet, Bozon ne donne jamais le chemin vers la ressource demandée, il envoie les headers correspondant au type mime puis le contenu du fichier, afin que l'utilisateur ne puisse localiser le fichier sur le serveur.

Du coup, si php echo une erreur, ça bousille le corps de l'image et elle est corrompue.
C'est sans doute un truc comme ça qui se passe: php ne trouve pas certains fichiers (normalement dans storage) et envoie une erreur. On ne la voie pas à l'écran parce que les headers envoyés sont ceux d'une image...

Là où ça coince, c'est quand les images envoyées dans un bozon neuf merdouillent quand même... 
Tu pars bien d'une install complètement propre et sans aucun dossier système au départ (thumbs/upload/private) ?

**Comment by fpp-gh** [comment]
Oui j'ai pas été clair dans le point 2), c'est bien config.php que j'ai édité de la même façon que pour la 2.3 (mais a posteriori), et là tout est revenu (sauf l'affichage des images :-)

Dans le "PS", j'ai fait rm -f et suis reparti d'un master 2.4 vierge, sans modifs de config.php, en chargeant juste les fichiers de tests.

Je ne vois pas pourquoi ma config PHP aurait changé depuis hier...
Y a moyen de récupérer un master 2.3 pour vérifier ?

PS : pour les erreurs PHP, effectivement, le message que j'ai recopié en 3) n'est pas du texte HTML, c'est le contenu de l'image...

**Comment by broncowdd** [comment]
Je viens de voir que j'ai aussi le souci d'affichage des images, c'est donc bien de ma faute, j'ai du faire une modif qui coince quelque part ^^ pas de problème, je bosse dessus et je te tiens au courant ;-)

**Comment by fpp-gh** [comment]
Ouf, me voilà bien soulagé, merci :-)

Et Cyrille avec ses 30.000 fichiers n'a rien vu ?? C't'un skhandâââlll ! :-)

![q3k8q0-l](https://cloud.githubusercontent.com/assets/4593667/13931110/14a71740-efa2-11e5-9d37-7161b31ec37e.jpg)

**Comment by broncowdd** [comment]
hinhin je viens de trouver: c'est en effet très con ^^ juste une chaine de caractère en début de share.php qui foutait le bran XD
My bad, je corrige direct ! Merci encore !

**Comment by cborne** [comment]
sortir du George Marchais avec en référence le bébète show, ça craint.

**Comment by fpp-gh** [comment]
Meuh, où ça le bébête-show ??...

**Comment by cborne** [comment]
c'est pas grave Elkabbach
