### ISSUE TITLE
Refresh bug

### ISSUE THREAD

**Issue by qwertygc** [broncowdd/BoZoN#105]
En local, j'ai foutu un copier collé de dossiers dans le répertoire de Bozon, mais je n'ai que le dossier principal, pas son contenu, malgré un rafraîchissement. une idée d'origine du bug ?

**Comment by broncowdd** [comment]
Je vais y reflechir, merci ;-)

Le 22 mars 2016 10:42:15 CET, Qwerty <notifications@github.com> a écrit :
>En local, j'ai foutu un copier collé de dossiers dans le répertoire de
>Bozon, mais je n'ai que le dossier principal, pas son contenu, malgré
>un rafraîchissement. une idée d'origine du bug ?
>
>---
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/broncowdd/BoZoN/issues/105

-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.

**Comment by broncowdd** [comment]
Au passage, les droits sur les fichiers colles sont-ils corrects (si bozon ne peut y acceder, il ne peut leur creer un id) ?

Le 22 mars 2016 10:42:15 CET, Qwerty <notifications@github.com> a écrit :
>En local, j'ai foutu un copier collé de dossiers dans le répertoire de
>Bozon, mais je n'ai que le dossier principal, pas son contenu, malgré
>un rafraîchissement. une idée d'origine du bug ?
>
>---
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/broncowdd/BoZoN/issues/105

-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.

**Comment by qwertygc** [comment]
OK sous Linux, pas OK sous windows.
