### ISSUE TITLE
Lightbox sous firefox/iceweasel

### ISSUE THREAD

**Issue by wiltur** [broncowdd/BoZoN#108]
La lightbox ne semble pas fonctionner sous firefox/iceweasel (vrai pour les deux), il m'arrive de voir les fleches/croix en bas, mais ça ne dure pas et ça passe directement à l'affichage de l'image de façon classique (url de l'image)

En revanche ça fonctionne sous chromium.

**Comment by broncowdd** [comment]
En effet, je viens de le constater... Je m'en occupe, merci ^^

**Comment by broncowdd** [comment]
J'ai arrangé ça, j'essaie de committer dans la soirée

**Comment by jerrywham** [comment]
J'ai apporté quelques (beaucoup ?) de modification à la lightbox. Je t'ai envoyé le fichier corrigé. Si tu peux y jeter un oeil...

**Comment by wiltur** [comment]
merci ça fonctionne très bien :)

(sans vouloir fait mon chieur, serait-il possible d'ajouter la navigation par clavier ? flèches droite/gauche = next/previous, Esc=fermeture de la lightbox)
