### ISSUE TITLE
Déplacer les fichiers de la racine vers un sous-dossier

### ISSUE THREAD

**Issue by jerrywham** [broncowdd/BoZoN#109]
Yop,
Salut l'ami ! Ça faisait longtemps dis donc !
Je reviens pour dénicher des bugs histoire que tu ne t'ennuies pas.
Je vais tenter de décrire ce qui arrive dans ce fil et en plus tenter de te donner une solution...

Lorsqu'on importe des fichiers pour la première fois, tout se passe bien. On crée un dossier dans le dossier uploads. Là aussi pas de problème.

Là où ça se corse, c'est quand on veut déplacer un fichier dans ce dossier nouvellement créé. On a bien le message disant que le fichier a bien été déplacer mais en fait, il n'en est rien.
Cela tient au fait que le premier caractère du fichier est un slash et la fonction check_path et bien elle n'aime pas ça.

Ce que je te propose, c'est donc d'ajouter la ligne suivante dans le fichier GET_POST_admin_data.php du core, ligne 209 :
` if ($file[0] == '/') { $file = substr($file,1);}`

Normalement, ça fonctionne

**Comment by broncowdd** [comment]
Salut copaing \o/
C'est cool, j'ai le beurre et l'argent du beurre... Merci !
J'ai ajouté ta modif... je committe un peu plus tard

**Comment by jerrywham** [comment]
Je viens d'en trouver un autre mais je n'ai pas encore la soluce. J'ouvre une nouvelle issue :D

**Comment by jerrywham** [comment]
Yo Bro,

Voici le fichier de lighbox.js modifié car il y avait quelques bugs 
(event non défini, variables non instanciées...) ce qui plantait le script.
J'ai également modifié le href des images via le script car si BoZoN est 
dans un sous-dossier, le fait de mettre "prev" ou "next" seuls ramène à 
la racine lors d'un clic.
De plus, j'ai modifié les fichiers footer.php et lightbox.html pour 
enlever les "type" dans l'appel de lb_show (car ça ne sert à rien dans 
la lighbox.

Voilou.

Bisou :D

Le 22/03/16 23:58, Bronco a écrit :
>
> Salut copaing \o/
> C'est cool, j'ai le beurre et l'argent du beurre... Merci !
> J'ai ajouté ta modif... je committe un peu plus tard
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub 
> <https://github.com/broncowdd/BoZoN/issues/109#issuecomment-200069421>
>

-- 
-- Cyril M. contact@ecyseo.net
