### ISSUE TITLE
Already done for upcoming version

### ISSUE THREAD

**Issue by broncowdd** [broncowdd/BoZoN#11]
# upcoming version 1.7.2
* focus field in rename input text #40 
* list layout #39 
* thumbnail deletion error #41 
* switch layout view in menu (icon<==>list)
* change theme in menu
* zip a folder #38 
* bugfix #44 
* bugfix #46

**Comment by cborne** [comment]
- je vois pas le lien vers github
- le panneau lattéral c'est mignon mais faudrait envisager de le fermer sur un clic à l'extérieur
- il manque le fichier img/file.png

**Comment by broncowdd** [comment]
* le lien est en footer
* le panneau se ferme maintenant en cliquant en dehors
* le précédent commit n'avait pas renvoyé d'erreur mais il manquait des fichiers: c'est corrigé ;-)

**Comment by cborne** [comment]
là si je télécharge c'est ok ?

**Comment by broncowdd** [comment]
yep :)

**Comment by cborne** [comment]
un flux rss par répertoire pour afficher les nouveautés ce serait super méga la classe

**Comment by yudi-ariyanto** [comment]
can user change their login password ?
