### ISSUE TITLE
Traduction de l'écran de config

### ISSUE THREAD

**Issue by Pluxopolis** [broncowdd/BoZoN#113]
- L'écran de configuration n'est pas traduit
- Déplacer les clés de traduction du fichier config_form_help.php dans les fichiers de langues du dossier /local
- Supprimer l'include du fichier config_form_help.php dans la fonction generate_config_form (core.php) 
- dans le fichier generate_config_form, on a la clé de traduction  'default_theme' => array('theme1','default'). La valeur theme1 ne correspond à rien (à supprimer)

**Comment by broncowdd** [comment]
oui, c'est du au fait qu'il s'agit d'une version où la config n'était pas terminée: elle l'est à présent mais je n'ai pas eu le temps de commiter ^^ j'essaie ce soir ! Merci
