### ISSUE TITLE
Ecran de config: chargement des valeurs

### ISSUE THREAD

**Issue by Pluxopolis** [broncowdd/BoZoN#114]
Les valeurs sélectionnées ne sont pas rechargées après la sauvegarde

Exemple: pour le paramètre default aspect
- sélectionner la valeur : icon (à la place de list)
- sauvegarder
au rechargement de la page c'est toujours la valeur list qui est affichée

idem pour les autres paramètres dans les listes déroulantes et les cases à cocher

**Comment by broncowdd** [comment]
Normal, la page config n'est pas terminée (j'ai juste oublié de virer 
l'icône du header^^⁾

Le mer. 23 mars 2016 à 12:57, Pluxopolis <notifications@github.com> a 
écrit :
