### ISSUE TITLE
Editeur markdown: image non trouvée (erreur 404)

### ISSUE THREAD

**Issue by Pluxopolis** [broncowdd/BoZoN#115]
Une erreur 404 est générée sur la page de l'éditeur markdown 

Failed to load resource: the server responded with a status of 404 (Not Found)

templates/default/css/img/noise.png

**Comment by broncowdd** [comment]
je ne pense jamais à virer cet appel à noise.png, je vais le faire de 
suite ;-)

Le mer. 23 mars 2016 à 13:00, Pluxopolis <notifications@github.com> a 
écrit :
