### ISSUE TITLE
License

### ISSUE THREAD

**Issue by juanito003** [broncowdd/BoZoN#12]
Hi, is there a license for BoZoN?
GPL , GPLv2, GPLv3, MIT, AGPL, WTFPL?

**Comment by broncowdd** [comment]
Good question ! ^^
I think Creative Common BY-NC-SA is a good one, I'll mention it inside the app's readme.
Feel free to fork and modify Bozon as you want and distribute it. I prefer to exclude commercial use and I think it's better to keep the free aspect of the app and it's forks.
You can also freely use the libs and parts of code you want in your own apps ;-)

**Comment by nodiscc** [comment]
CC Licenses are strongly discouraged for software: see https://github.com/sebsauvage/MinigalNano/issues/96

**Comment by broncowdd** [comment]
Mmmm, good advice, thanks ^^ What is your opinion : what licence should I use ?

**Comment by nodiscc** [comment]
Check http://choosealicense.com/ and https://tldrlegal.com/licenses/browse. I suggest AGPL (GPL variant for network services, which adds the requirement to point users to the source code) if you care about modifications being Free too, or MIT or WTFPL if you just don't care and are ok for your code to be used in closed-source applications.

**Comment by broncowdd** [comment]
Ok, thanks again ;-)
I think AGPL looks cool.

**Comment by broncowdd** [comment]
added in 1.5
