### ISSUE TITLE
upload fichier

### ISSUE THREAD

**Issue by ilood** [broncowdd/BoZoN#123]
Bonjour,

J'ai installé le BoZoN dans l'autre serveur, quand je voudrais upload file: j'ai rencontré le message : 
xx.pdf [application/pdf, 481] The file doesn't fit

Le fichier n'est pas téléchargé. 

Mais si on installe le BoZoN dans locale PC, il n'y a pas le problème pour upload files.

**Comment by jerrywham** [comment]
Quel est la taille de ton fichier ? Quels sont les limites de ton deuxième serveur ? (voir le php.ini)

**Comment by ilood** [comment]
Bonjour, 

Ce problème n'existe plus.
