### ISSUE TITLE
2.4 build 3 vers 4

### ISSUE THREAD

**Issue by fpp-gh** [broncowdd/BoZoN#124]
Arf. Je viens de passer à la build 4 et plus de BoZon du tout (page blanche).

Le log nginx est farci de ce type d'erreur :

>  [error] 12759#0: *4425 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Can't use function return value in write context in /usr/share/nginx/www/bozon/core/core.php on line 32" while reading response header from upstream

Oooops.

**Comment by broncowdd** [comment]
Curieux, je n'ai rien de tel, je regarde asap (là j'ai la maison pleine d'enfants ^^)

**Comment by fpp-gh** [comment]
Y a pas le feu, je suis aussi at home donc pas grand besoin du bozon :-)

**Comment by fpp-gh** [comment]
Yep avec les bugfix de ce matin ça remarche, merci !!
