### ISSUE TITLE
Problème premier démarrage/installation

### ISSUE THREAD

**Issue by michelwend** [broncowdd/BoZoN#125]
Au premier démarrage de bozon 2.4 build 5 j'ai le message d'erreur suivant:
Warning: file_put_contents(private/config.php): failed to open stream: No such file or directory in /home/web11372/web/doc/core/core.php on line 176
Message qui n'apparait plus lors du deuxième démarrage

**Comment by broncowdd** [comment]
Ok, merci, je corrige asap ;-)

**Comment by michelwend** [comment]
Désolé mais j'ai le même type d'erreur pour bozon 2.4 build 6
Warning: file_put_contents(private/config.php): failed to open stream: No such file or directory in /home/web11372/web/doc/core/core.php on line 179

**Comment by jerrywham** [comment]
Vérifie les droits en écriture du dossier private

**Comment by michelwend** [comment]
D'accord il faut les mettre en 755? Pour l'instant ils sont en 0744. Ce qui est quand même étonnant c'est que cela se produit une seule fois...

**Comment by juanito003** [comment]
Je viens d'installer bozon pour la première fois et j'ai la même erreur en ayant fais un git clone du dépot. Et effectivement ça s'affiche une fois, après on dirait que tous ce qui est manquant est crée et en rafraichissant la page la seconde fois c'est bon.

**Comment by broncowdd** [comment]
Je rebosse dessus ;-) Merci !

**Comment by michelwend** [comment]
Bonjour,
En version 8 je n'ai plus le problème.

**Comment by broncowdd** [comment]
de rien ;-)
