### ISSUE TITLE
Upload .epub : forbidden

### ISSUE THREAD

**Issue by Draky50110** [broncowdd/BoZoN#130]
Hello.

J'essaye d'envoyer un fichier .epub : Mary_Shelley-Frankenstein_ou_le_Promethee_moderne.epub mais il me dit "forbidden file format".

Est-il possible de choisir quel format peut être téléversé ?
Via admin de préf. mais sinon autoriser les epubs en "dur" dans le code ?

Merci :)

**Comment by broncowdd** [comment]
dans la page de config, il y a une option allow unknown filetypes, essaie de l'activer pour voir.

**Comment by Draky50110** [comment]
J'ai mis à jour en 2.4b6 et changé la variable dans config.php mais... y'a plus de zone d'upload ?
J'ai loupé un truc ?

**Comment by aledeg** [comment]
Dans la barre d'outil située en haut de la page, tu as un bouton "Upload". Quand tu cliques dessus, la zone d'upload apparait.

**Comment by Draky50110** [comment]
Ok, j'avais un souci de cache navigateur, j'avais 4 icônes en haut à gauche maintenant j'en ai BEAUCOUP plus ;)

Problème réglé :)

**Comment by aledeg** [comment]
:+1:
