### ISSUE TITLE
Passer la limite des 2 MB

### ISSUE THREAD

**Issue by fidoboulettes** [broncowdd/BoZoN#131]
Bonjour,
je ne crois pas que ce "problème" ai été traité... je voulais donc savoir s'il était possible d'uploader des fichiers de taille >2MB? (En fait, ne pas avoir de limitation du tout).

Si oui, comment faire? J'ai regardé dans le fichier de conf mais n'ai rien trouvé.

Merci de votre aide et du travail que font bronco (et cyrille)

**Comment by cborne** [comment]
c'est une limitation qui vient du php.ini de ton serveur / hébergeur

fidoboulettes <notifications@github.com> a écrit :

> Bonjour,
> je ne crois pas que ce "problème" ai été traité... je voulais donc
> savoir s'il était possible d'uploader des fichiers de taille >2MB? (En
> fait, ne pas avoir de limitation du tout).
>
>   Si oui, comment faire? J'ai regardé dans le fichier de conf mais n'ai
> rien trouvé.
>
>   Merci de votre aide et du travail que font bronco (et cyrille)
>
>   —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub[1]
>       



Liens:
------
[1] https://github.com/broncowdd/BoZoN/issues/131

**Comment by timovn** [comment]
Dans le fichier php.ini, il faut mettre par exemple `20M` sur la ligne `upload_max_filesize`, au lieu de 2M.

Si tu es chez un hébergeur, demande lui si c’est possible (certainement non, mais tu peux demander…) ou regarde dans les paramètres de ton compte (cPanel?) si c’est possible de changer la limite.

**Comment by fidoboulettes** [comment]
Super, merci de votre aide... Je connaissais pas. Je l'ai passé à 2go pr être large...
