### ISSUE TITLE
bozon sur alternative.to

### ISSUE THREAD

**Issue by cborne** [broncowdd/BoZoN#14]
alternative.to est pour moi la référence quand je cherche autre chose dans les logiciels du marché. Il serait peut être judicieux de l'inscrire. Il y a un formulaire en anglais, mon niveau n'est pas assez bon pour le faire.

**Comment by broncowdd** [comment]
ça ne m'était même pas venu à l'esprit, alors que c'est aussi ma référence...
J'admets que ce serait carrément la classe ^^

**Comment by cborne** [comment]
ben vas y. Après j'utiliserai mes charmes de blogueur populo pour 
envoyer les gens liker.

**Comment by broncowdd** [comment]
cool ^^ ;-)

**Comment by cborne** [comment]
tu me diras quand tu l'as fait j'irai racoler derrière.

**Comment by broncowdd** [comment]
Dès qu'on a une version stable, propre et complète, je le fais ;-)
