### ISSUE TITLE
Affichage: emplacement des liens (Gérer les fichiers / Gérer les liens)

### ISSUE THREAD

**Issue by nIQnutn** [broncowdd/BoZoN#144]
Encore un petit bug d'affichage.
Selon le mode, le lien se fait la mal.
![capture d ecran 2016-04-22 a 00 38 04](https://cloud.githubusercontent.com/assets/13441278/14726485/fa7db236-0822-11e6-8d69-8e5183809939.png)
![capture d ecran 2016-04-22 a 00 38 17](https://cloud.githubusercontent.com/assets/13441278/14726486/fa800892-0822-11e6-8171-0eb9541fd09a.png)

**Comment by broncowdd** [comment]
oui, je vois ce que c'est
