### ISSUE TITLE
Upload hasardeux selon type MIME

### ISSUE THREAD

**Issue by Nh3xus** [broncowdd/BoZoN#147]
Bonjour,

Je rencontre des soucis en essayant d'envoyer certains fichiers sur BoZon, quelque soit leur type MIME.

Certains types de fichiers sont ils interdits par défaut ?

Exemple : certains fichiers MP3 et M3U8 passent mais pas d'autres.

Apache 2.4.16
PHP 5.6.20
MariaDB 5.5.43

Merci.

**Comment by broncowdd** [comment]
Avez-vous essayé de régénérer la base, pour voir ?
Le fichier existe-t-il (via ftp par exemple)?
Tenez-moi au courant ;-)

**Comment by Nh3xus** [comment]
Je viens de régénérer la base, mais ça ne fonctionne pas.

le fichier n'est pas présent sur le système (vérifié via un ls par SSH)

**Comment by jerrywham** [comment]
Quelle est la taille des fichiers qui ne passent pas et quelle est la limite imposée dans le php.ini de ton serveur (à la fois celle des upload mais aussi celle des formulaires) ?
PS : pour info, BoZon n'utilise pas de base de données...

**Comment by Nh3xus** [comment]
Vous avez raison.

Après avoir augmenté les paramètres upload_max_filesize et post_max_size, tout fonctionne.

Je vous remercie, j'ai appris à mieux configurer le fichier php.ini grâce à vous :)

Ce bug n'en est donc pas un.
