### ISSUE TITLE
Erreur version : 1.5 -> 1.4.2

### ISSUE THREAD

**Issue by cborne** [broncowdd/BoZoN#15]
Il faudrait regarder si c'est juste un oubli ou s'il y a autre chose

**Comment by cborne** [comment]
le tri est plus en alpha, je sais pas sur quoi c'est trié d'ailleurs

**Comment by cborne** [comment]
et le RSS on y accède comment ?

**Comment by broncowdd** [comment]
Pour le rss (comme le json) c'est sur la page index, quand on accède au lien de partage.
Plus simplement, tu auras le liens de partage auquel on ajoute «&rss» ou «&json»

Par contre, je n'ai pas saisi le problème de tri ?

**Comment by cborne** [comment]
je n'ai plus le tri en ordre alphabétique sur mes fichiers dossiers.

**Comment by broncowdd** [comment]
Je viens de m'en rendre compte: c'est dû à la suppression du recours à glob au profit du fallback seul (sur free ça posait quand même des problèmes). Du coup, il faut effectuer un tri du tableau avant le return dans la fonction _glob() du core.php. Je fais ça de suite ;-)

**Comment by broncowdd** [comment]
Voilà, c'est modifié.

**Comment by cborne** [comment]
et nouveauté j'ai le htaccess à la racine qui apparaît alors qu'il 
apparaissait pas

j'espère que tu es content pour le repos que je t'ai accordé :D

**Comment by broncowdd** [comment]
Oui, je me suis éloigné bien sept minutes mouhouhaha ! 
Ce bug là sera facile a gérer: un filtrage conditionnel dans _glob et voilà. 
Je fais ça tt à l'heure, là je suis au jardin ;-)

Le 2 août 2015 15:41:11 CEST, Cyrille BORNE <notifications@github.com> a écrit :
>et nouveauté j'ai le htaccess à la racine qui apparaît alors qu'il 
>apparaissait pas
>
>j'espère que tu es content pour le repos que je t'ai accordé :D
>
>Le 02/08/2015 15:37, Bronco a écrit :
>>
>> Je viens de m'en rendre compte: c'est dû à la suppression du recours
>à 
>> glob au profit du fallback seul (sur free ça posait quand même des 
>> problèmes). Du coup, il faut effectuer un tri du tableau avant le 
>> return dans la fonction _glob() du core.php. Je fais ça de suite ;-)
>>
>> —
>> Reply to this email directly or view it on GitHub 
>>
><https://github.com/broncowdd/BoZoN/issues/15#issuecomment-127024898>.
>>
>
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/broncowdd/BoZoN/issues/15#issuecomment-127025116

-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.

**Comment by cborne** [comment]
profite, je devrais pas tarder à partir à la plage.

**Comment by broncowdd** [comment]
Profite aussi alors ;-)


Le 2 août 2015 15:47:54 CEST, Cyrille BORNE <notifications@github.com> a écrit :
>profite, je devrais pas tarder à partir à la plage.
>
>Le 02/08/2015 15:47, Bronco a écrit :
>> Oui, je me suis éloigné bien sept minutes mouhouhaha !
>> Ce bug là sera facile a gérer: un filtrage conditionnel dans _glob et
>
>> voilà.
>> Je fais ça tt à l'heure, là je suis au jardin ;-)
>>
>> Le 2 août 2015 15:41:11 CEST, Cyrille BORNE
><notifications@github.com> 
>> a écrit :
>> >et nouveauté j'ai le htaccess à la racine qui apparaît alors qu'il
>> >apparaissait pas
>> >
>> >j'espère que tu es content pour le repos que je t'ai accordé :D
>> >
>> >Le 02/08/2015 15:37, Bronco a écrit :
>> >>
>> >> Je viens de m'en rendre compte: c'est dû à la suppression du
>recours
>> >à
>> >> glob au profit du fallback seul (sur free ça posait quand même des
>> >> problèmes). Du coup, il faut effectuer un tri du tableau avant le
>> >> return dans la fonction _glob() du core.php. Je fais ça de suite
>;-)
>> >>
>> >> —
>> >> Reply to this email directly or view it on GitHub
>> >>
>>
>><https://github.com/broncowdd/BoZoN/issues/15#issuecomment-127024898>.
>> >>
>> >
>> >
>> >
>> >---
>> >Reply to this email directly or view it on GitHub:
>> >https://github.com/broncowdd/BoZoN/issues/15#issuecomment-127025116
>>
>> -- 
>> Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma 
>> brièveté.
>>
>> —
>> Reply to this email directly or view it on GitHub 
>>
><https://github.com/broncowdd/BoZoN/issues/15#issuecomment-127025355>.
>>
>
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/broncowdd/BoZoN/issues/15#issuecomment-127025385

-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.
