### ISSUE TITLE
Can't delete, rename, move files

### ISSUE THREAD

**Issue by PeterTGarner** [broncowdd/BoZoN#154]
* System: Linux odroid1 3.10.92 #1 SMP PREEMPT Tue Nov 17 00:15:24 BRST 2015 armv7l armv7l armv7l GNU/Linux 
* Web server: nginx/1.9.3 (ubuntu) 
* Installed using: git clone https://github.com/broncowdd/BoZoN.git bozon

I have installed 2.4 build 12 and upload is working well. However, I cannot  delete, rename or move files to another folder. There are no errors in my logs (attached, redacted) - can you please help?

Thanks!

[access.log.txt](https://github.com/broncowdd/BoZoN/files/256974/access.log.txt)
[config.php.txt](https://github.com/broncowdd/BoZoN/files/256975/config.php.txt)

**Comment by PeterTGarner** [comment]
I apologise - today it is working. I have no idea what caused this (non) problem. All is good. Thank you for great software!

**Comment by broncowdd** [comment]
Dont worry and thanks a lot ;-)
