### ISSUE TITLE
[OVH] Erreur 500 sur téléchargement de fichier MD

### ISSUE THREAD

**Issue by Zilkos** [broncowdd/BoZoN#156]
Bonjour,

J'ai installé BoZon sur un mutualisé OVH (PHP 5.6) et je rencontre un souci d'erreur 500 au téléchargement d'un fichier MD présent dans uploads/user/. Aussi bien en téléchargement depuis l'interface que depuis un lien de partage.

J'ai trouvé un fix un peu crade (n'étant pas développeur PHP) mais ce n'est sans doute pas une solution définitive, bien pour ça que je poste une issue et pas une PR.

Dans core/share.php, faire sauter le if suivant:

```php
if ($ext=='md'){
    include('core/markdown.php');
    require(THEME_PATH.'/header_markdown.php');	
    echo $qrcode;
    echo  parse(url2link(file_get_contents($f)));
    echo $call_qrcode;
    require(THEME_PATH.'/footer_markdown.php');
}
```

(et changer le `else if` suivant en `if` bien évidemment)

En n'entrant pas dans ce if on peut:

  - Télécharger le fichier sans problème 
  - Disposer de l'éditeur MD et de la preview
  - Partager le fichier (et le télécharger depuis un lien de partage) sans problème.

Je sais que c'est clairement crade, mais si toutefois ça peut aider pour une release suivante, c'est toujours ça... D'autant que je ne sais pas si ça peut venir de l'infra OVH, donc à prendre avec des pincettes.

Bien évidemment, je suis ouvert à tous les types de test depuis un mutu OVH si besoin d'aide.

o/

**Comment by broncowdd** [comment]
Super ! Tu remonte un bug et tu proposes une correction \o/ Merci ! 
Je vais regarder de plus près ;-)

**Comment by Zilkos** [comment]
Mais de rien, ce projet me plait beaucoup, je cherchais quelque chose de léger, sans base, et uniquement pour des fichiers, donc ça remplit à 100% mes besoins.

Encore une fois, je ne suis pas dev PHP (je dev d'autres choses donc je comprends l'algo en place), il faut voir ça comme un hook temporaire au cas où si quelqu'un rencontre le bug.

Outre cette petite modification, je n'ai aucune idée d'où ça peut venir (subtilité de l'infra OVH, le code, etc).

o/

**Comment by broncowdd** [comment]
C'est corrigé: Je faisais un include d'une lib que j'incluais dès le départ du script -> erreur ^^
Merci encore ;-)
