### ISSUE TITLE
Menu contextuel utilisation

### ISSUE THREAD

**Issue by qwertygc** [broncowdd/BoZoN#16]
Pourquoi pas utiliser un menu contextuel (https://developer.mozilla.org/en-US/Add-ons/SDK/Tutorials/Add_a_Context_Menu_Item ou https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XUL/PopupGuide/ContextMenus) pour gérer les dossiers : renommer, les liens, déplacer les fichiers… ?)

Sinon, pourquoi pas importer plusieurs fichiers à la fois ? (multiple import)

et pour déplacer les dossiers/fichiers, pourquoi pas utiliser le drag and drop ?

**Comment by broncowdd** [comment]
N'hésite pas à être plus spécifique ;-)

**Comment by qwertygc** [comment]
C'est à dire ? (désolé, j'ai envoyé sans texte, j'ai écrit ce qu'il manquait)µ.

**Comment by broncowdd** [comment]
hinhin, oui, du coup les posts se sont croisés :-D

**Comment by broncowdd** [comment]
De bonnes questions ^^
* Le drag & drop pour les fichiers était lourd à mettre en place (pour moi du moins ;-) et requérait deux "fenêtres" ouvertes: la source et la destination. Cette méthode m'a paru plus simple et légère quoique moins... habituelle.
* importer plusieurs fichiers ? le drag et drop sur la dropzone gère le drop multiple et donc l'upload de plusieurs fichiers à la fois. Pour l'import de fichier via l'url, ce serait possible mais il faudrait trouver une normalisation pour le collage des liens (séparateurs par exemple)
* Le menu contextuel: j'avoue ne pas y avoir pensé. à creuser, en effet ^^

**Comment by cborne** [comment]
le menu contextuel ne ferait que surcharger l'interface qui me parait 
suffisamment claire comme ça.

**Comment by qwertygc** [comment]
A moins que le Grand Maitre Poutreur Cyrille fasse une objection, il est possible de changer le design ? Je peux tenter de faire un truc pour le rendre moins kitsh (prend pas mal Bronco, les goûts et les couleurs… l'une des rare raison qui m'empêche de migrer Owncloud --> Bozon, c'est le design)

**Comment by broncowdd** [comment]
Pas de soucis pour moi ;-) c du design de codeur... Propose ;-)

Le 2 août 2015 17:45:25 CEST, Qwerty <notifications@github.com> a écrit :
>A moins que le Grand Maitre Poutreur Cyrille fasse une objection, il
>est possible de changer le design ? Je peux tenter de faire un truc
>pour le rendre moins kitsh (prend pas mal Bronco, les goûts et les
>couleurs… l'une des rare raison qui m'empêche de migrer Owncloud -->
>Bozon, c'est le design)
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/broncowdd/BoZoN/issues/16#issuecomment-127037463

-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.

**Comment by qwertygc** [comment]
![nomfichier](https://cloud.githubusercontent.com/assets/4261986/9026890/225413d4-3940-11e5-9f97-cccd8e794061.png)

J'avais fait ça pour un autre projet, je peux te filer les sources et tu peux faire joujou avec ?

**Comment by broncowdd** [comment]
J'adore faire joujou ;-) je regarde asap ce soir. Merci :)

Le 2 août 2015 17:59:15 CEST, Qwerty <notifications@github.com> a écrit :
>![nomfichier](https://cloud.githubusercontent.com/assets/4261986/9026890/225413d4-3940-11e5-9f97-cccd8e794061.png)
>
>J'avais fait ça pour un autre projet, je peux te filer les sources et
>tu peux faire joujou avec ?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/broncowdd/BoZoN/issues/16#issuecomment-127039608

-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.

**Comment by qwertygc** [comment]
```
* {
	margin:0;
	padding:0;
	box-sizing: border-box; 
}

html {
	min-height:100%;
	color:#61666c;
	font-weight:400;
	font-size:1em;
	font-family:'Open Sans', sans-serif;
	line-height:2em;
	width:90%;
	margin:auto;
}
body {
	padding:20px;
}
a {
	color:#61666c;
	text-decoration:none;
}
a:hover {
	color:#2a2a2a;
}
table {
	width:100%;
	border-collapse:collapse;
	font-size:.875em;
}
tr {
	outline:0;
	border:0;
}
tr:hover td {
	background:#f6f6f6;
}
th {
	text-align:center;
	font-size:.75em;
	padding-right:20px;
}
/* 2nd Column: Filename */

td {
	padding:5px 0;
	outline:0;
	border:0;
	border-bottom:1px solid #edf1f5;
	vertical-align:middle;
	text-align:center;
	transition:background 300ms ease;
}
td:first-of-type  {
	text-align:left;
}
td a{
	display: block;
}
#dropArea {
	background: #fff;
	border: 1px solid #999;
	font-size: 2em;
	color:#999;
	height: 2em;
	line-height: 2em;
	text-align: center;
	border-radius:5px;
}
```
```
<!doctype html>
<html>
<head>
<link rel="stylesheet" href="application/style.css"/>
<title>Directory</title>
</head>
<body>
<header>Home</header><table>
<tr><th>File</th><th>Size</th><th>Last Modified</th></tr></table><div class="upload"><div id="dropArea">&#8613;</div><div><span id="count"></span></div><div id="resultupload"></div></div>
</body>
</html>
```

**Comment by broncowdd** [comment]
Ajout de themes pour la prochaine version #11
