### ISSUE TITLE
Telecharger un "gros" Zip de dossier

### ISSUE THREAD

**Issue by SimpleHomeUser** [broncowdd/BoZoN#168]
Bonjour,

Quand je veux télécharger un zip d'un dossier un peu gros (115Mo) je reçois ce message:
Sous Chrome:
La page xxx.org ne fonctionne pas
xxx.org n'a envoyé aucune donnée.
ERR_EMPTY_RESPONSE

sous Firefox
Secure connection failed
The connection to the server was reset while the page was loading.
...

Le fichier zip est bien dans le répertoire temp (il fait 83Mo)
Il semble que ca prenne trop de temps a faire le zip et que les navigateurs lachent l'affaire.

Je sais pas si il y a un timeout à configurer qqpart.

**Comment by broncowdd** [comment]
D'autant plus curieux que le timout est mis à 0 (pas de limite)...
C'est en local ? Sur un serveur distant ?

**Comment by SimpleHomeUser** [comment]
C'est sur un vps ovh
Ca le fait dès que c'est un peu long de faire le zip.
A la louche lorsque que le dossier fait 100Mo

**Comment by broncowdd** [comment]
Je vais tester de mon côté

**Comment by CyberTroll** [comment]
J'ai le même problème, je suis chez O2switch, testé sous debian, windows (Firefox et Chrome).

**Comment by broncowdd** [comment]
J'ai testé chez o2switch sans souci... curieux...
Je vais essayer de voir ça...

**Comment by broncowdd** [comment]
J'ai fait un correctif que je vais tester avant de le poster...
