### ISSUE TITLE
Suggetion : tooltip

### ISSUE THREAD

**Issue by Draky50110** [broncowdd/BoZoN#17]
Hello.

Multiplication des possibilités c'est bien.
Mais je suis paumé sur les icônes.
Possible de mettre un tooltip au survol (hoover) ?

Merci :)

**Comment by broncowdd** [comment]
En effet: si je ne l'ai pas fait, c'est pour éviter le surchargement de code html. Entre temps, j'ai eu une autre idée pour ajouter cette fonction sans alourdir. => ToDo #3
