### ISSUE TITLE
[Résolu] - Problème curl

### ISSUE THREAD

**Issue by Tos26** [broncowdd/BoZoN#185]
Après installation de la version 2.4 build 15 from scratch, j'ai le message : Curl n'est pas installé sur ce serveur.
Or curl est installé. 
Ma config :
NGINX version 1.2.1
Curl version 7.26.0
Raspberry pi B+

Quel est le souci ?

**Comment by broncowdd** [comment]
Bozon teste l'existence de la fonction curl_init()
```if (empty($_SESSION['curl'])){$_SESSION['curl']=function_exists('curl_init');}```
Peut-être est-ce un souci avec nginx ? (je n'ai jamais bossé avec, il faut que je l'installe pour tester)
Je me documente... merci pour le retour ;-)

**Comment by broncowdd** [comment]
Si tu n'as pas peur de modifier des trucs, je te propose de tester quelque-chose:
Dans le fichier core/core.php, à la ligne 50, remplace
```if (empty($_SESSION['curl'])){$_SESSION['curl']=function_exists('curl_init');}```
par
```if (empty($_SESSION['curl'])){$_SESSION['curl']=extension_loaded('curl');}```

Peut-être cela fonctionnera-t-il mieux.
Tiens-moi au courant ;-)

**Comment by Tos26** [comment]
Merci pour tes réponses. Je teste ce soir et te fais un retour.

**Comment by broncowdd** [comment]
ok ;-)

**Comment by Tos26** [comment]
J'ai remplacé la ligne en question, sans résultat.
J'imagine que sans curl, le transfert de fichier ne fonctionne pas?

**Comment by Tos26** [comment]
Pour information, j'ai vu que dans core.php, il y a beaucoup d'accès au fichier htaccess, or celui-ci n'existe pas avec NGINX. Une piste peut-être ?

**Comment by ewilly** [comment]
as-tu installer php5-curl & php5-gd ?
si ça peut t'aider bozon est pleinement fonctionnel sur yunohost/raspbian+raspberry, l'application est [ici](https://github.com/YunoHost-Apps/bozon_ynh) tu pourras y trouver des paramètrages qui pourraient te donner des pistes : un nginx fonctionnel (à adapter) + un php-fpm + éventuellement le script d'install
PS : tes versions nginx et curl sont bien vielles, tu es sur quel OS ?

**Comment by Tos26** [comment]
Merci ewilly, Il me manquait php5-curl.
Plus de problème de Curl non installé :)

Et merci aussi pour ton lien qui confirme ce que je soupçonnais: La config par défaut de bozon n'est valable que pour apache. Il convient d'adapter pour nginx, notamment par rapport aux fichiers htaccess, non gérés par nginx.
Je posterai le détail des résultats de mes changements.

En ce qui concerne l'âge de mes versions, je suis sur raspbian wheezy, donc effectivement pas jeune. Il faudrait que je migre vers jessie.

**Comment by broncowdd** [comment]
Merci à tous pour toutes ces interventions !
