### ISSUE TITLE
[Résolu] - Formulaire de login disparaît après un clic

### ISSUE THREAD

**Issue by Tos26** [broncowdd/BoZoN#186]
Après installation de la version 2.4 build 15 from scratch, j'ai voulu créer l'admin, mais lorsque je clique sur un des champs Login / Mot de passe / Confimation, le formulaire entier disparaît, ne reste que la page blanche sous le bandeau avec le logo bozon. Le formulaire semble toujours présent puisque actif mais non visible.

Ma config :
NGINX version 1.2.1
Firefox version 49.0.2
Raspberry pi B+

**Comment by broncowdd** [comment]
Tiens ?! Voilà qui est étrange en effet !
Donc, si j'ai bien compris, le formulaire disparaît quand on clique dans un des champs...
Tu as des extensions dans ton firefox ?

**Comment by Tos26** [comment]
J'utilise µblock origin et un script greasemonkey pour Anti-Adblock killer. (Désactivation sans effet) 
Il se passe la même chose qu'avec la page d'accueil, celle avec les logos PHP, JS, CSS et HTML. On peut la retirer en cliquant n'importe où, n'est-ce pas ? Et bien, le comportement du formulaire semble être le même: un clic efface tout (page blanche) et le formulaire reste actif mais invisble.

Ce ne serait pas lié à au système utilisé pour effacement de la page d'accueil ?

**Comment by broncowdd** [comment]
donc ce n'est pas le navigateur ?! 
Tu es le premier à remonter ce comportement étrange: sur la page d'accueil, il n'y a rien qui soit censé disparaître non plus oO
Il n'y a pratiquement pas d'appels ajax donc les pages sont chargées telles qu'elles...
Vraiment curieux... tu pourrais me faire un gif animé de ce qui se passe sur l'écran ?

**Comment by Tos26** [comment]
Je t'ai fait un gif animé. Je ne comprends pas ce qui se passe au niveau de la page d'accueil si rien n'est censé disparaître : J'ai une info bulle qui indique "Click to remove".

Je te laisse regarder ça et on en reparle ;)
![out](https://cloud.githubusercontent.com/assets/23366980/20193061/a983c7bc-a78c-11e6-9fbc-7c6d402f6e67.gif)

**Comment by Tos26** [comment]
Bonjour Bronco,

Des idées suite aux dernières infos données sur mes problèmes ?

**Comment by Tos26** [comment]
Cette ligne dans index.php semble être la cause de la disparition des formulaires:

`if (!empty($message)){echo '<div class="info" onclick="addClass(this,\'hidden\');" title="'.e('Click to remove',false).'">'.$message.'</div>';}`

Il me semble que ceci est actif quand on a une erreur comme moi, du type Curl non installé.
J'ai commenté cette ligne et là je retrouve une interface normale, mais toujours impossible de se connecter.
Toujours pas de solution pour Curl ...
Des infos sur comment convertir les fichiers htaccess en données digérables par NGINX ?

**Comment by Tos26** [comment]
Je confirme donc que ce problème est bien dû à l'absence de Curl. Après installation de php5-curl, plus de disparition de formulaire.
Il serait peut-être judicieux de revoir le code ci-dessus, à moins que ce soit vraiment le comportement désiré.
Et aussi, préciser que php5-curl est une dépendance nécessaire.
Merci à ewilly pour son aide sur Curl (et le reste...)

**Comment by broncowdd** [comment]
Oui, avec le gif c'est plus clair ^^ ce doit être une balise non fermée ;-)
Ma faute !
ça ne le fait plus en V3.0 (bon, faut dire que je suis reparti de zéro aussi :D)
