### ISSUE TITLE
[Résolu] - Impossible de se logger

### ISSUE THREAD

**Issue by Tos26** [broncowdd/BoZoN#187]
Après installation de la version 2.4 build 15 from scratch, j'ai créé l'admin (en utilisant la touche tab, voir ticket #186).
Le dossier private est bien créé, avec un certain nombre de fichiers à l'intérieur (auto_restrict_data.php, auto_restrict_users.php etc...).
Lorsqu'ensuite, je veux me logger, après validation du login/mot de passe, je ne suis pas connecté et je reviens sur la page d'accueil.
Pour rappel, j'ai le message "Curl n'est pas installé" voir ticket #185. Je ne sais pas si c'est lié, genre tant que la config n'est pas complète, login impossible ????

Ma config :
NGINX version 1.2.1
Curl version 7.26.0
Raspberry pi B+

**Comment by broncowdd** [comment]
Normalement, l'absence de zip/curl etc n'empêche pas l'utilisation de Bozon, elle ne fait qu'en limiter les possibilités.

Si le login n'aboutit pas, c'est qu'il y a un souci:
* dans le couple login/passe
* dans la session (gestion de la session/incohérence des données etc)
* dans les tokens (mauvias token ou token absent)

C'est assez difficile d'en savoir plus à distance... 
As-tu la possibilité de le tester sur le RPI avec apache, pour savoir si ce serait une incompatibilité avec NGINX ?

**Comment by Tos26** [comment]
Il me semble avoir respecter la procédure standard:
je n'ai pas changé le chemin vers les dossiers upload, private dans config.php. ils se retrouvent donc dans /var/www/bozon/ et appartiennent au groupe et user www-data.
A la première connexion, j'ai rempli mon login, mot de passe et confirmation du mot de passe. Après validation, j'ai à nouveau une fenêtre de connexion sans la confirmation du mot de passe, donc pour moi on est bien dans une phase de login et pas de création de compte, preuve que celle-ci semble être validée. Ensuite pas de connexion.

En ce qui concerne Apache, ce n'est pas très facile à tester car il faudrait que je reconfigure tout mon serveur. S'il y a un problème lié à NGINX, il me semble plus utile de corriger ça pour faire avancer le projet Bozon, qui doit fonctionner quelque soit le serveur utilisé.

**Comment by broncowdd** [comment]
Oui, bien entendu, je parlais du serveur apache seulement pour tester si
le pb venait de la relation Bozon/Nginx, histoire de ne pas creuser le
sujet pour rien et de cibler l'origine du problème: je n'ai pas
l'intention de lâcher les utilisateurs de nginx ;-)

**Comment by Tos26** [comment]
Ok.

Pour info, j'ai volontairement entré un mauvais mot de passe pour me connecter et j'ai bien un message Wrong combination login/pass.

**Comment by Tos26** [comment]
Voici le contenu du dossier private après une creation de compte.
![2016-11-10-221735_1571x269_scrot](https://cloud.githubusercontent.com/assets/23366980/20194664/966ff3a6-a793-11e6-81b2-1ca1173a48a7.png)

**Comment by Tos26** [comment]
Après avoir installé php5-curl, je n'arrive pas à me logger: après création de mon compte bozon, un login me ramène systématiquement à la page d'accueil. J'ai bien compris que nginx demande une config particulière car ne gère pas les fichiers htaccess. Suivant les infos [https://github.com/YunoHost-Apps/bozon_ynh](url) (merci ewilly), j'ai tenté de modifier mon fichier de config nginx dans sites-available. Avec, je gère deux applis différentes en PHP.
Voici ma config:

`server { 
	listen 443 ssl; 
	#access_log /var/www/logs/access.log;
	#error_log /var/www/logs/error.log;
        ssl_certificate /etc/nginx/cert.pem; 
	ssl_certificate_key /etc/nginx/cert.key; 
        root /var/www/; 
	index index.php index.html index.htm; 

        location /cops/ {
		try_files $uri $uri/ /index.php;
      		auth_basic "Vous devez vous authentifier"; 
      		auth_basic_user_file /etc/nginx/.htpasswd/.cops;
        }

        location /bozon/ {

		location ~ (uploads|thumbs){
       		         deny all;
       		 }
	
		location ~ private {
			deny all;
			location ~* /temp/.*\.zip$ {
				allow all;
			}
		}
	        
		location ~ core {
			deny all;
			location ~* \.js$ {
				allow all;
			}
		}
	}

	location ~ \.php$ {
		fastcgi_split_path_info ^(.+\.php)(/.+)$;
		fastcgi_pass unix:/var/run/php5-fpm.sock;
		fastcgi_index index.php;
		fastcgi_param HTTPS on; 
		include fastcgi_params;
	}

}`

Je débute dans la config nginx, donc si quelqu'un peut m'aider et me dire ce qui n'est pas correct, merci d'avance

**Comment by ewilly** [comment]
essaie de mettre `try_files $uri $uri/ /index.php;` directement à al racine sous `index index.php index.html index.htm; `

**Comment by Tos26** [comment]
J'ai déplacé la ligne à la racine, sans résultat...

Là je sais plus trop. Le reste du fichier de conf est bon ? En fait je me suis inspiré de tes conseils ewilly [ici](https://github.com/YunoHost-Apps/bozon_ynh) mais il semble que tu as rajouté la config spéciale pour les dossiers private, uploads et core directement dans le fichier nginx.conf.
Or je l'ai mis dans mon fichier de conf sous sites-available. C'est correct ?

**Comment by Tos26** [comment]
Quelqu'un peut-il m'expliquer le rôle du fichier banned_ip_'suite de chiffre à rallonge'.php ?
A la première tentative de connexion, ce fichier est généré dans le dossier private. est-ce normal?

**Comment by broncowdd** [comment]
oui, le fichier est généré par défaut: il contient les ip ayant provoqué un problème de sécurité.

**Comment by Tos26** [comment]
Donc s'il est vide (c'est mon cas), pas de bannissement en cours.

Peux-tu me donner quelques pistes de recherche sur mon problème de connexion? Parce-que là, je sèche:
Les droits et permissions sur les dossiers semblent bons: 755
La config NGINX, en remplacement des fichiers htaccess, est issue des conseils de ewilly et me semble correcte.
Tous les dossiers bozon appartiennent aux groupes et utlisateurs www-data.
La création du compte admin semble fonctionner.
Lorsque je rentre un mauvais mot de passe lors de la connexion, bozon me l'indique.

Malgré tout ça, après une tentative de connexion, je reviens systématiquement à la page d'accueil. J'essaierai de poster un gif animé pour illustrer ça...

Merci de ton aide.

**Comment by Tos26** [comment]
Voici le gif animé:

![out](https://cloud.githubusercontent.com/assets/23366980/20572283/2c0df0f4-b1ab-11e6-83c8-57f2739c9d67.gif)

**Comment by broncowdd** [comment]
Et si c'était un souci de token ou de session ?
Je regarde...

**Comment by broncowdd** [comment]
essaie de remplacer auto_restrict avec celui-là: s'il y a une erreur de token, on le verra
[auto_restrict.php.zip](https://github.com/broncowdd/BoZoN/files/609651/auto_restrict.php.zip)

**Comment by Tos26** [comment]
Ok j'ai testé.

Après tentative de connexion, j'ai une page blanche avec "referer error!"
Une piste ?

**Comment by Tos26** [comment]
Info de dernière minute (erreur de ma part lors de l'édition du fichier):
Le fichier banned_ip_'xx'.php n'est pas vide!
Voici son contenu:
`<?php /*Banned IP*/ $auto_restrict["banned_ip"]=array (
  '192.168.0.254' => 
  array (
    'nb' => 4,
    'date' => 1479926036,
  ),
  '165.225.76.85' => 
  array (
    'nb' => 2,
    'date' => 1479805139,
  ),
  '192.168.0.10' => 
  array (
    'nb' => 3,
    'date' => 1479922267,
  ),
) ?>
`

**Comment by broncowdd** [comment]
ok ça m'aide... il y a donc un souci avec le referer...
du coup, pour lui, la sécurité n'est pas assurée et il refuse l'accès...
En ligne 535, tu mets return true pour bypasser la détection du referer et voir s'il y a une autre erreur...

**Comment by Tos26** [comment]
Ok. Je teste ce soir et je te tiens au courant.
Merci.

**Comment by Tos26** [comment]
broncowdd,
J'ai donc rajouté return true; à la ligne 535 ==> ça marche !!!!

Alors en regardant le code de auto_restrict.php dans la section REFERER (j'y connais rien en PHP), j'ai cru comprendre qu'il y a un lien avec le nom de domaine. Donc à tout hasard, j'ai modifié la conf d'NGINX en y ajoutant la ligne : server_name mon_adresse_IP. (il est vrai que je ne l'avais pas encore fait).
Ensuite, j'ai testé l'accès dans ce contexte, après avoir remis le fichier auto-restrict.php d'origine:
==> ça marche !!!

Ma conclusion: le nom de domaine doit être défini dans le fichier de config NGINX du site.
Tu confirmes ?

**Comment by broncowdd** [comment]
Boooon, on avance ! ^^
Je pense en effet que ça doit être un truc comme ça... Ouf !

**Comment by Tos26** [comment]
Oui on peut dire que c'est soldé.

Avant de cloturer le ticket, une dernière question (puisque je te tiens ;) ):
J'ai commencé à jouer avec bozon et après avoir modifié php.ini pour monter la taille limite d'upload à 20 Mo, je ne peux uploader que des fichiers inférieurs à 1 Mo. Pourtant la limite de 20 Mo est bien prise en compte par bozon, la preuve en image:

![2016-11-24-210759_1918x1056_scrot](https://cloud.githubusercontent.com/assets/23366980/20609261/61bdc5be-b28a-11e6-9c6f-26eb4c36df80.png)

Qu'est-ce que j'ai encore loupé ?
(Si tu préfères que j'ouvre un autre ticket, dis le moi)

**Comment by Tos26** [comment]
Bon du coup, j'ai fouillé un peu, c'est encore un problème de config de NGINX:

Dans le fichier nginx.conf, j'ai rajouté la ligne : client_max_body_size 100m;
Et là c'est tout bon:

![2016-11-24-213327_1918x1056_scrot](https://cloud.githubusercontent.com/assets/23366980/20609516/fcdc0d5a-b28d-11e6-8463-3c2c59687891.png)

Cette fois, je tag le ticket en résolu.
Encore merci pour tout et, surtout, super travail. Bozon correspond exactement à ce que je cherchais.
Vivement la version 3 !!!!

**Comment by briceparmentier** [comment]
Bonjour !

J'ai suivi le sujet avec Tos26 (un collègue de boulot) sur le problème de connexion et la solution du server_name dans la conf nginx.

Je ne suis pas encore rentré dans le code de BoZoN pour fouiller par moi-même, mais je me heurte à un problème : ma box n'acceptant pas le NAT loopback (accès aux équipements locaux sur le réseau local avec mon DynDNS), j'accède à BoZoN de l'extérieur avec mon dns, et de l'intérieur (réseau local) avec l'adresse IP.
Suis-je donc obligé de mettre deux clauses server_name dans nginx ? Ou n'y a-t-il pas une subtilité dans le code PHP qui restreint ce type d'accès qu'il serait possible d'éditer ?

Merci d'avance !
Brice
