### ISSUE TITLE
Enlever mot de passe : cadenas plutôt que reload ?

### ISSUE THREAD

**Issue by Draky50110** [broncowdd/BoZoN#19]
Salut

Pour mettre un mot de passe, on clique sur le cadenas.
Pour l'enlever... faut "recréer" le lien.
Possibilité de virer le mot de passe sans changer de lien, genre on clique le cadenas, on entre rien (champ vide) et hop ?

**Comment by broncowdd** [comment]
Oui, en faisant la FAQ je me suis fait la même réflexion, le problème vient du fait que pour avoir un lien protégé par mot de passe, il faut changer l'ID (qui devient un hash de vérification du mot de passe)... par conséquent, il est impossible de retirer le mot de passe en gardant le lien, puisque ce dernier est lié au mot de passe.

**Comment by Draky50110** [comment]
Ok, dans ce cas, vu qu'en dessous tu indiques comment mettre le mot de passe, tu peux peut-être préciser "Pour l'enlever, utiliser la regénération de lien" et pour cet icône, dire qu'en plus de changer le lien ça enlève le mot de passe (au cas où la perosnne ne ferait pas gaffe).

**Comment by broncowdd** [comment]
Pas bête en effet... => todo #3
