### ISSUE TITLE
Undefined index in BoZoN/core/listfiles.php on line 45, 46 and 47

### ISSUE THREAD

**Issue by jerrywham** [broncowdd/BoZoN#191]
icon_close, icon_rename, icon_move ne sont pas définies dans la variable $templates.
Qu'a voulu dire l'auteur ??? :p

**Comment by broncowdd** [comment]
Hinhinhin, l'auteur a voulu dire qu'il convient de regarder les lignes 53 à 69 du fichier templates.php dans lequel on crée les index en fonction des fichiers html présents dans le dossier templates ^^
(c'est pas toujours de ma faute quand même ;-)
Allez, bisou malgré tout !

**Comment by jerrywham** [comment]
Ah, tu as modifié le dossier templates...
Coquin ! J'avais pas vu.
