### ISSUE TITLE
getUrl donne une url tronquée. Utiliser getRacine à la place.

### ISSUE THREAD

**Issue by jerrywham** [broncowdd/BoZoN#192]
Dans core/core.php, modifier la ligne 52 par 
```php
if (empty($_SESSION['home'])){$_SESSION['home'] =getRacine();}	
```
Sinon, quand le port est indiqué dans l'url (typiquement lorsqu'on utilise MAMP sur le port 8888) les liens de partage sont tronqués et le port n'apparait pas (dans le lien pour les flux RSS et JSON par exemple).

**Comment by broncowdd** [comment]
pointu ça ^^ j'aurais jamais pensé ;-) Merci

**Comment by briceparmentier** [comment]
Ah bien ça ! Je l'avais vu aussi, je voulais poser un ticket, mais je ne serais surement pas allé jusqu'à trouver quelle ligne il fallait modifier.
Perso j'ai le soucis car j'accède à mon serveur BoZon hébergé chez moi depuis l'extérieur via un DynDNS et une règle NAT sur ma box donc je dois spécifier le port :)
