### ISSUE TITLE
Cannot login

### ISSUE THREAD

**Issue by josch** [broncowdd/BoZoN#194]
Hi,

i just unzipped the latest BoZoN release on my server, created a new user and then tried to log in.

Unfortunately, it seems that my login remain without effect because after logging in, I still see the exact same view as before with the "Connect" button on the upper-right-hand side.

Which log can I show you to figure out what went wrong?

**Comment by briceparmentier** [comment]
Hello, check the issue #187 , maybe you will be able to gather some information. In this issue, it is a problem with the web server configuration.
Cheers

**Comment by josch** [comment]
Do you also have some simple instructions in English? :)

**Comment by briceparmentier** [comment]
Ha yes sorry ;)
Which server application did you use ? Tos26, author of the #187 issue, is using nginx, and the error was in the "server_name" clause in the server default configuration. This server_name clause must have a value corresponding to the address you use to access your BoZoN instance.
For example this can be the ip address of the device if you are only browsing the server from your local network.

**Comment by josch** [comment]
Yes, nginx. Yes, that worked!

Is there something that BoZoN can do to auto-detect this mis-configuration of the webserver and warn the user about it?

Could this problem be documented in the setup instructions?

**Comment by josch** [comment]
And two more questions:

 - is it a planned feature to allow users that receive a share link to view the photos that a directory contains in the form of a photo gallery (show photos in larger size and let them easily go from one to the next)?
 - is it a planned feature to allow users that receive a share link to also upload their own content into that directory without them having an account?

**Comment by briceparmentier** [comment]
For the nginx configuration, that's a good question. I'm waiting for brocon's answer on this.
In my usecase, I can access the BoZoN instance from the local network or from the outside, so that I use two different addresses, and I don't know how to deal with that.

For the two other questions I can't answer, maybe those should be treated in another issue as they don't really match this issue subject ;)

**Comment by broncowdd** [comment]
>Is there something that BoZoN can do to auto-detect this mis-configuration of the webserver and warn the user about it?
>Could this problem be documented in the setup instructions?

Sure, it'll be explained in the future wiki/faq on the official website... I try to complete the V3 before that ^^ (I'm out of time ! ;-)


>is it a planned feature to allow users that receive a share link to view the photos that a directory contains in the form of a photo gallery (show photos in larger size and let them easily go from one to the next)?

You mean like a portfolio I guess... Why not, it's not a hard feature to add :-)


> is it a planned feature to allow users that receive a share link to also upload their own content into that directory without them having an account?

NO, ABSOLUTELY NOT ! ;-) It should be a actual server's murder ! Imagine a noob user trying to upload a large set of 15Mpx photos oO ...
Worse, imagine a user using your bozon to store illegal files,
Even worse, imagine a hacker uploading some nasty files to hack your bozon... 

Regards

**Comment by josch** [comment]
Hi,

Quoting Bronco (2017-01-13 22:42:36)
> > is it a planned feature to allow users that receive a share link to also
> > upload their own content into that directory without them having an
> > account?
> 
> NO, ABSOLUTELY NOT ! ;-) It should be a actual server's murder ! Imagine a
> noob user trying to upload a large set of 15Mpx photos oO ...

that just means I have to be careful whom to give the share-link to.

> Worse, imagine a user using your bozon to store illegal files,

that just means I have to trust the person I give the share link to.

> Even worse, imagine a hacker uploading some nasty files to hack your bozon...

that just means that the share link has to have a random part that is close to
impossible to guess.

For example I can tell owncloud to generate a url of the form:

https://foo.com/public.php?t=0123456789abcdef0123456789abcdef

Whoever has that link can then upload things into that directory. Since that
link has a long id it is close to impossible to guess by people who could try
and upload something malicious.

cheers, josch

**Comment by broncowdd** [comment]
There's so much methods to steal an URL (browser history first but not only)...
The "guest" account can be a solution: create a temp account for this person could do the trick.

**Comment by josch** [comment]
Which methods to steal a URL are there other than having access to the user's computer? Via https, the exact GET request is hidden from third parties.

To follow up on your example, for the malicious party to have access to the browser history, they would have to have access to the user's computer. At that point, it would not help if the user had a temporary account because that malicous party could then do the same things via that account.

So I do not understand what makes such a URL less secure than a "temporary account". In some sense, that URL represents such a "temporary account". The hash is the login data that gives those who have the information permission to upload to a certain directory.

Could you expand on your reasoning?

**Comment by broncowdd** [comment]
It's always possible to access a computer, even remotely.
A temporary account can be limited or erased easily without any change in Bozon's code... so I don't understand why not to use a feature whitch is already implemented and more secure (the admin always has the possibility to remove the account, the user needs the login/password combination to connect & upload, not only the url etc.)

**Comment by josch** [comment]
Your argument does not make any sense. If you postulate that a computer can *always* be accessed remotely then your whole security model breaks down and no security measure makes sense. Security is not binary but is multiple shades of gray. There exists no perfectly secure system so the task is to come up with thread models and evaluate them.

You say a temporary account can be erased. True. But in the same way a temporary url can be invalidated by the user who shared it.

A login/password combination has the same level of security as having the credential in the URL. Whoever knows the login/password can carry out the uploads. Whover knows the secret URL can carry out the upload. In practice it doesn't make it differently secure whether I share a secret user/pass tuple or a secret URL. In both cases, the "secret" information has to somehow be sent to the recipient's computer and then continues existing on that computer. So the methods to obtain either are the same. If you deem the URL to be less secure, then please explain why.

You are right that the desired functionality can already be done with existing functionality. The disadvantage lies in the usability. Here is a practical example from my recent past. I got married and everybody took photos. In owncloud it was easy to create a directory and send the secret URL with upload rights to all interested parties. In BoZoN this would not easily be possible. I would have to manage over 120 temporary account, somehow make up some user names and passwords and send individual emails to all interested parties. This is clearly more work than just having a single secret URL that everybody knows about.

**Comment by broncowdd** [comment]
> Your argument does not make any sense.
Ok, so let stop it right here...

**Comment by spacegaucho** [comment]
Hi all, sorry for reviving this thread. I'm having a similar issue while trying to login. 

Also using nginx, but with the correct parameters for server_name in nginx.conf. 

Running centos7 and php7. Fpm and nginx use are running on the same user (nginx). Selinux disabled for testing purposes.

![out](https://cloud.githubusercontent.com/assets/15604339/23097624/d3f84238-f616-11e6-944e-92f134f41dc3.gif)

As you can see it seems to be a session/redirect issue as the authentication process goes right; notice my "on purpose" wrong login attempt.

Any insight would be very appreciated.
