### ISSUE TITLE
Reflected XSS vulnerability

### ISSUE THREAD

**Issue by whitehataudit** [broncowdd/BoZoN#199]
Hi,

I've discovered a reflected XSS vulnerability in the application. Here's is an example URL (woks in Firefox and Internert Explorer):
https://[Bozon's root URL]/index.php?p=" ONLOAD=alert("XSS")> 

In this case attack string is inserted to the following HTML code:
`<body class="" ONLOAD=alert("XSS")> body_hu view list ">`

Regards,
Tamas

**Comment by broncowdd** [comment]
Hi and thanks for this, I fix it right now ;-)
