### ISSUE TITLE
Quelques erreurs

### ISSUE THREAD

**Issue by cborne** [broncowdd/BoZoN#20]
PHP Fatal error:  Maximum execution time of 60 seconds exceeded in /srv/web/web/bozon/index.php on line 47 

Cette erreur me gêne dans sa logique. En fait le gars il va pouvoir télécharger un fichier pendant une heure et ça va planter au bout de 1 heure 5. En relevant l'exécution à 7200 on fait tout passer. Pourquoi ça passe pour 30 ou 40 minutes et ça plante quand on dépasse un peu les 1 heures, ça devrait planter à 60 secondes. 

De la même manière : 

PHP Warning:  date() [<a href='function.date'>function.date</a>]: It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected 'Europe/Berlin' for 'CEST/2.0/DST' instead in /srv/web/web/bozon/index.php on line 90

C'est un collègue en Allemagne effectivement. 

Il manque toujours le favicon

**Comment by broncowdd** [comment]
L'erreur de temps d'exécution est en effet étrange: le script fait ce qu'il a à faire, à savoir envoyer les headers et le contenu, ce qui est rapide quel que soit le volume du fichier... le script ne continue pas à s'exécuter après le début du téléchargement et il n'y a donc pas de raison de se trouver en face de cette erreur. Curieux.
Pour la date, par contre, c'est tout-à-fait courant et facilement corrigeable ;-) 
Je todo.

**Comment by cborne** [comment]
et pourtant je te confirme le problème, je vais tenter de diminuer le 
temps d'exécution, 7200 me parait tout de même excessif mais en levant 
le plafond c'est passé tout seul.

**Comment by broncowdd** [comment]
Vraiment curieux... 7200, c'est juste... énorme.

**Comment by cborne** [comment]
je peux faire les test en baissant néanmoins à plus d'une heure d'attente le test, c'est lourdingue.

**Comment by broncowdd** [comment]
Ben oui, c'est clair ...
Ceci dit, on pourrait envisager une redirection simple pour les gros fichiers, ce qui libérerait le script plus tôt en lançant le téléchargement dans le navigateur comme un lien normal... je vais tester quelque chose dès que possible ;-)

**Comment by broncowdd** [comment]
Mouaip... la redirection en js n'empêche pas d'obtenir le lien direct vers le fichier, ce qui annulerait l'anonymisation de l'accès à la ressource.
...

**Comment by cborne** [comment]
je vais quand même faire des tests pour voir à combien ça passe. Tomber 
à 3600 pour rire par exemple

**Comment by broncowdd** [comment]
Je ne comprends pas: le script ne continue pas à s'exécuter, pourquoi cette erreur...?!
Sinon, un set_time_limit(0); en début de fichier index.php pourrait résoudre le problème (en ligne 7 par exemple, avant le reste du code)

**Comment by cborne** [comment]
et y a rien dans readfile ou dans autre chose qui pourrait faire quelque 
chose ?

**Comment by broncowdd** [comment]
ben non... readfile est fait pour ça. :-/
en gros, soit c'est le combo header+readfile soit c'est la redirection...
le set_time_limit(0); est à tester quand même...

**Comment by cborne** [comment]
je le case à quelle ligne ?

**Comment by broncowdd** [comment]
dès le début après les commentaires (l 7)

**Comment by cborne** [comment]
A priori ça passe. J'espère que tu es content des tests extrêmes, faut 
que je vois avec un collègue qui a la fibre sur des fichiers de plus de 2 Go

**Comment by broncowdd** [comment]
\o/ heureusement que c'est toi qui fais ce genre de test! j'aurais pas eu la patience XD

Le 6 août 2015 00:12:35 CEST, Cyrille BORNE <notifications@github.com> a écrit :
>A priori ça passe. J'espère que tu es content des tests extrêmes, faut 
>que je vois avec un collègue qui a la fibre sur des fichiers de plus de
>2 Go
>
>Le 05/08/2015 22:20, Bronco a écrit :
>>
>> dès le début après les commentaires (l 7)
>>
>> —
>> Reply to this email directly or view it on GitHub 
>>
><https://github.com/broncowdd/BoZoN/issues/20#issuecomment-128135501>.
>>
>
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/broncowdd/BoZoN/issues/20#issuecomment-128165018

-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.
