### ISSUE TITLE
Incorrect password on shared link returns blank page

### ISSUE THREAD

**Issue by greecemunky** [broncowdd/BoZoN#201]
I have password-protected a shared link.  When I follow the link and enter the password, if I enter a correct password it works and the file starts downloading, however if I enter an incorrect password it returns a blank page.

Tested using latest master (haven't tried other releases).

Suggestion (if repeatable): return a HTML page advising of failed password and ask to re-enter password, or return page advising of failed password and include share link user can click to retry.

**Comment by broncowdd** [comment]
Yes, it could be better ^^
It's already done in V3 ;-)
