### ISSUE TITLE
Nom du fichier pour les lien public

### ISSUE THREAD

**Issue by PeuX** [broncowdd/BoZoN#203]
Bonjour
et avant tout great work !!!

dans certain cas les fichiers que je télécharge depuis bozon sont nommé index.php,
pour corriger le soucis j'ai juste ajouté
`header('Content-Disposition: attachment; filename="'._basename($f).'"');`
ligne 85 dans core/share.php
ça règle mon soucis, mais je ne sais pas si ça à des effets de bord... (je suis en version 2.4 build 16)

Bonne journée

**Comment by broncowdd** [comment]
j'ai modifié, merci ;-)
