### ISSUE TITLE
Partage de fichier text

### ISSUE THREAD

**Issue by tatapoum** [broncowdd/BoZoN#204]
Bonjour,

Je souhaite partager un fichier text, par exemple :
https://yunh.le-henanff.fr/bozon/index.php?f=1589c3e40871e9

Le contenu du texte est affiché avec une mise en page "BoZon" mais je m'attendrais à ce que mon navigateur me propose de télécharger le fichier.

Est-ce que c'est lié à BoZon ou peut-être à mon navigateur ?
Ca se passe "normalement" depuis ma page d'administration de fichier avec le clic gauche sur le fichier (mais pas à l'ouverture vers un autre onglet).

**Comment by broncowdd** [comment]
C'est assez simple: il suffit d'aller dans la page de config et de changer l'extension txt de ligne.
![image](https://cloud.githubusercontent.com/assets/4249696/22861986/c9bc2ce4-f125-11e6-954e-dd65e3991b05.png)

devient 

![image](https://cloud.githubusercontent.com/assets/4249696/22861990/ee73b930-f125-11e6-8296-ca3d09a4f807.png)
Et voilà ;-)

**Comment by tatapoum** [comment]
Argh, c'était tout bête...
Je n'avais pas été faire un tour dans les préférences.
Désolé du dérangement et bravo pour le boulot accompli !!
