### ISSUE TITLE
drag and drop sur les dossiers

### ISSUE THREAD

**Issue by cborne** [broncowdd/BoZoN#21]
Ma femme va être utilisatrice de bozon, du fait qu'elle est instit elle est pétrie de tas de sous dossiers. Si je lui dis qu'il faut qu'elle fasse la création de chaque dossier puis faire le drop des fichiers dedans, ça va pas le faire. 

Au départ, je pensais pas ça utile mais finalement ça serait pas du luxe.

**Comment by broncowdd** [comment]
J'y ai pensé: le probléme reste qu'il est impossible d'uploader des dossiers en js... Mais j'ai une alternative: uploader un zip qui se dézippe une fois sur le serveur... 
Ça fonctionnera sans problème, à priori... 

Le 5 août 2015 22:32:16 CEST, Cyrille BORNE <notifications@github.com> a écrit :
>Ma femme va être utilisatrice de bozon, du fait qu'elle est instit elle
>est pétrie de tas de sous dossiers. Si je lui dis qu'il faut qu'elle
>fasse la création de chaque dossier puis faire le drop des fichiers
>dedans, ça va pas le faire. 
>
>Au départ, je pensais pas ça utile mais finalement ça serait pas du
>luxe. 
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/broncowdd/BoZoN/issues/21

-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.

**Comment by broncowdd** [comment]
Sinon, en attendant, l'accès en ftp devrait compenser, non ?

**Comment by cborne** [comment]
ma femme en FTP ... AH AH AH !!! Je vais uploader ses fichiers par le 
ftp puis laisser les manips complémentaires par bozon. Sinon tu es forcé 
de coder un outil de synchro.

**Comment by broncowdd** [comment]
Heu... oui, mais non en fait ^^
Le zip, elle saura faire ? ;-)

**Comment by cborne** [comment]
oui pour le zip
