### ISSUE TITLE
Search (filter) not recursively finding files in subfolders

### ISSUE THREAD

**Issue by InfiniFlix** [broncowdd/BoZoN#214]
When I choose the search/filter icon and enter the filename of a file, in a sub folder, I do not get any results.

Can the search be made recursive and also not case sensitive?

Thanks!

**Comment by broncowdd** [comment]
Ooops, that's definetly not a feature: it's an issue ^^
I'll fix it asap, thanks a lot ;-)

**Comment by broncowdd** [comment]
Ok, you can try this version ;-)

**Comment by hubce** [comment]
Hey thank you, recursive and not case sensitive search works, it's now a feature!

**Comment by broncowdd** [comment]
\o/
