### ISSUE TITLE
Login page - Can it be default?

### ISSUE THREAD

**Issue by ambipur76** [broncowdd/BoZoN#228]
Can BoZoN configured or modified in order to start BoZoN with the login page instead of the default index.php ?

**Comment by broncowdd** [comment]
The current version can't, but I'll think about it for the next one ;-)

**Comment by jerrywham** [comment]
If you want, you can add this to templates/default/home.php :
```<script type="text/javascript">document.location="index.php?p=login";</script>```
It's ugly but it works.

**Comment by ambipur76** [comment]
Hi, thank you! That is exactly what I was expecting!
