### ISSUE TITLE
[Bug] Transformation d'un fichier en répertoire quand on clique dessus

### ISSUE THREAD

**Issue by Draky50110** [broncowdd/BoZoN#23]
Salut

Je viens de mettre à jour et quand je clique sur un fichier, au lieu de.. le visualiser/lancer (?), il essaye de l'ouvrir comme un répertoire.
Screenshot : https://lut.im/XEwSDA0o/AeekJcf5

**Comment by broncowdd** [comment]
C'est curieux que l'erreur se situe dans auto_dropzone, qui est indépendant du reste de l'appli et ne gère que le glisser déposer upload...
As-tu changé des droits d'accès ou quelque chose dans le genre ?

**Comment by Draky50110** [comment]
J'ai DL master.zip de GitHub et j'ai décompressé en écrasant les fichiers.

**Comment by broncowdd** [comment]
ça vaudrait le coup de regarder les droits des fichiers dossiers... même si j'ai un doute.

**Comment by Draky50110** [comment]
Pas besoin, je gère en SSH donc j'ai forcément les droits.
Je perds le lien desfichiers déjà uploadés si je vire tout sauf "uploads" et "user" ou je ne sais quoi lié au login ?

**Comment by broncowdd** [comment]
C'est bon, j'ai refait le bug: je bosse dessus ;-)

**Comment by broncowdd** [comment]
Ok, j'ai trouvé: c'est lors du passage aux templates que j'ai modifié la forme du lien... c'est réparé pour la prochaine version ;-)
Merci pour le retour

**Comment by Draky50110** [comment]
Ok.
J'ai les commits en RSS donc c'est nickel :)
