### ISSUE TITLE
Vitesse ? 

### ISSUE THREAD

**Issue by cborne** [broncowdd/BoZoN#24]
Je viens d'avoir la riche idée de mettre à jour et il se produit quelque chose d'assez étonnant. Un download à l'extérieur de bozon 230 ko/s, un download issu de bozon 6 ko/s :D

**Comment by cborne** [comment]
alors le problème va se poser lorsque le fichier devient plus gros genre dès 700 Mo. Il faut dire que je ne fais pas beaucoup d'effort car j'ai changé de serveur et j'ai seulement 1 Go de RAM que je vais monter un cran dessus. Là je suis en train de downloader une version 1.5 pour voir si le bug est similaire dans cette configuration.

**Comment by cborne** [comment]
le problème est le même sur une version 1.5. Demain je monte un peu plus de RAM pour voir si ça vient de là

**Comment by cborne** [comment]
alors ça vient de ma machine certes mais c'est quand même franchement bizarre, quand je clique depuis mon navigateur sur le lien en direct sans passer par bozon ça mouline pas et ça rame pas.

**Comment by cborne** [comment]
à 3 Go de RAM ça passe quelle que soit la taille du fichier, il faudrait vérifier sur des configurations type PI2 limitée à 1 Go pour voir si c'est pareil. Il y a quand même quelque chose quelque part dans Bozon qui pose des problèmes à la RAM

**Comment by broncowdd** [comment]
\o/ yes, un bug ^^
Plus sérieusement, le lien direct ne passe pas par php, donc la puissance du serveur n'y fait rien... par contre, quand le lien est géré par bozon, c'est php qui s'en charge... 
Toutefois, de là à avoir de telles différences .. c'est énorme.

**Comment by broncowdd** [comment]
Je pense que php n'est clairement pas fait pour gérer seul de tels volumes de données...
Resterait une redirection simple au lieu de l'envoie des données brutes:
lien bozon->redirection vers le lien réel du fichier (mais on perd l'anonymisation du chemin sur le serveur, encore une fois)

**Comment by broncowdd** [comment]
Là je bosse sur un thème elementaryOS pour BoZon ^^, ça commence à être joli ;-)

**Comment by cborne** [comment]
et j'ai pas testé la fonctionnalité du zip :D

j'ai toujours ça qui traine : [Sat Aug 29 09:41:53 2015] [error] PHP 
Notice:  Undefined index: HTTP_ACCEPT_LANGUAGE in 
/srv/web/web/bozon/core.php on line 354, referer:  /bozon/admin.php

**Comment by cborne** [comment]
la perte de l'anonymisation remettrait en cause totalement le principe 
de fonctionnement de bozon, ce n'est pas le but, on va donc dire que je 
l'utilise de façon extrême. Il faudrait toutefois regarder comment s'y 
prend cozycloud ou des programmes comme girafeau pour gérer, pour voir 
si le problème est le même.

Dans la documentation tu devrais préciser qu'il faudrait imaginer ne pas 
dépasser les fichiers d'une certaine taille. Néanmoins ça va pas très 
loin puisqu'avec 1 Go de RAM, 400 Mo d'occupés par ipfire ça bloquait 
sur des fichiers de 200 Mo ce qui n'est pas grand chose.

**Comment by cborne** [comment]
tiens tu vas être content je viens de faire le test du zip et ça marche 
même avec des sous répertoires

**Comment by broncowdd** [comment]
oui, t'as vu ? ;-) c'était la solution la plus simple ^^
Je suis de ton avis pour la redirection...
Pour les limites, il faudrait en effet le préciser en attendant mieux...
Un oeil sur cozycloud serait en effet intéressant. Je ne connais pas girafeau.
