### ISSUE TITLE
Hey... you were banished, fuck off !

### ISSUE THREAD

**Issue by cborne** [broncowdd/BoZoN#27]
1) je trouve la skin elementary très vilaine
2) je lis la doc, je change dans default pour mettre default, j'en profite pour changer la langue. Je fais un refresh, rien ne change
3) je lance chromium qui n'a pas de cache qui m'affiche la bonne version
4) je vide le cache de firefox, je me déconnecte de bozon
5) Hey... you were banished, fuck off ! quel que soit le navigateur.

**Comment by broncowdd** [comment]
1-    T'es dur, quand même ! ça m'a pris un temps ! ^^ (mais moi je préfère :P)
2-4  Que le changement de skin ne s'applique pas de suite, c'est normal, la config étant mise en session il faut fermer la fenêtre et rouvrir bozon pour le voir s'afficher.
5-    Ce message survient quand il y a eu des choses anormales dans le déroulement de la sécurisation et qu'on a atteint la limite de nombre de problèmes.
Il peut s'agir d'un blème de token (repost d'un formulaire-> bing), d'un login erroné, d'un souci de referrer, du post d'un formulaire trop vieux (les tokens ont une durée de vie)  etc.
Tu peux changer la tolérance aux problèmes dans auto_restrict :
- l 54: $auto_restrict['IP_banned_expiration_delay']
- l 55: $auto_restrict['max_security_issues_before_ban']
- l 58: $auto_restrict['tokens_expiration_delay']
- l 61: $auto_restrict['use_ban_IP_on_token_errors']

Par défaut, ton ip est ban  90 secondes (pour éviter le brute force).
