### ISSUE TITLE
Bouton purger pour les logs

### ISSUE THREAD

**Issue by cborne** [broncowdd/BoZoN#30]
Au bout de 100 pages ça pourrait devenir lassant

**Comment by broncowdd** [comment]
J'y pense ;-)
Là je teste une version reprise par Oros qui a fait un superbe travail de sécurisation.

**Comment by broncowdd** [comment]
fait sur la version 1.7

**Comment by cborne** [comment]
fait sur la version 1.7, c'est très bien, mais si on met à jour depuis 
la version 1.6 en 1.7, ça tourne ou j'explose l'installation ?

**Comment by broncowdd** [comment]
Bonne question... 
A priori, je dirais que non, mais ça vaut le coup de tester quand même...

**Comment by cborne** [comment]
c'est donc une invitation au voyage et au crash de mon installation à 
nouveau. Tu sais me vendre du rêve.

**Comment by broncowdd** [comment]
t'as vu ! ^^
Je pense que ça ne doit rien changer car les chemins correspondant aux ids sont relatifs à la racine uploads/
Mais ça se tente mon général.

**Comment by broncowdd** [comment]
Je pensais à toi : je dois migrer un disque dur qui menace de rendre l'âme, une chouette config comme t'aime... deux partoches : un windows avec le grub et mon home... mon install de mint est sur un autre... je sens que ça va être du grand mendez ! ^^

**Comment by cborne** [comment]
tu sais que j'aime vivre dangereusement moi aussi

**Comment by cborne** [comment]
bon je viens de mettre à jour, à part m'avoir purgé intégralement mon 
fichier de logs, pour l'instant rien de choquant. Merci pour cette purge !

**Comment by cborne** [comment]
et bien évidemment il a régénéré l'intégralité des liens !

**Comment by cborne** [comment]
ah et ce serait sympa de pouvoir faire un copier coller pour faire des 
whois sur l'ip

**Comment by broncowdd** [comment]
S'il a régénéré les liens, c'est parce qu'il a créé le dossier contenant le fichier ID puis il l'a régénéré...
L'ancien fichier ID se trouve toujours à la racine: je pense que si tu le mets dans le dossier private/, tu retrouveras les anciens liens...
