### ISSUE TITLE
bug mise à jour 1.7

### ISSUE THREAD

**Issue by cborne** [broncowdd/BoZoN#31]
Il m'a fait un dossier upload dans upload, ce qui fait que j'ai dû déplacer l'intégralité de mes fichiers à l'intérieur de ce sous répertoire. 

Que ça me foutrait en l'air l'intégralité de mes liens de partage ne m'étonnerait que vaguement.

ce que je te confirme en direct live !

**Comment by broncowdd** [comment]
Zut flute et cacaboudin... Je regarderai demain. :-/

Le 13 septembre 2015 20:34:42 CEST, Cyrille BORNE <notifications@github.com> a écrit :
>Il m'a fait un dossier upload dans upload, ce qui fait que j'ai dû
>déplacer l'intégralité de mes fichiers à l'intérieur de ce sous
>répertoire. 
>
>Que ça me foutrait en l'air l'intégralité de mes liens de partage ne
>m'étonnerait que vaguement.
>
>ce que je te confirme en direct live !
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/broncowdd/BoZoN/issues/31

-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.

**Comment by cborne** [comment]
on a un moyen de récupérer les anciennes versions de bozon, parce que je 
pense que ça peut être nécessaire assez régulièrement :D

**Comment by Draky50110** [comment]
@cborne via les commits sur github, oui
https://github.com/broncowdd/BoZoN/commits/master => tu cliques sur le bouton <> et ensuite tu arrives sur le github à ce commit et ensuite sur le "download zip" sur la droite.

**Comment by cborne** [comment]
Merci Gilles, c'est fait

**Comment by cborne** [comment]
c'est un problème de chmodage ou de chown ce qui est sûr c'est que même en 777 ça pose problème.

**Comment by cborne** [comment]
bon tu as regardé ?

**Comment by broncowdd** [comment]
Pas eu le temps ces derniers jours... J'essaie de m'y coller ce soir... 

Le 24 septembre 2015 07:21:23 CEST, Cyrille BORNE <notifications@github.com> a écrit :
>bon tu as regardé ?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/broncowdd/BoZoN/issues/31#issuecomment-142814399

-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.

**Comment by cborne** [comment]
ça roule. Je crois savoir de quoi tu parles quand tu dis pas le temps ...

**Comment by broncowdd** [comment]
Hahahaha... démarrage de mon pc de bureau: «le demarrage du serveur x a echoue» 
Hahahahahahahahahahaaaa... j'aurais pas du essayer d'installer les pilotes ATI proprios hier-soir.
Bon, ben je vais arranger ça... ;-)

**Comment by broncowdd** [comment]
Juste un mot en passant pour dire que je bosse sur le blème: j'ai trouvé d'où ça venait et c'est corrigé, toutefois, il faut à présent traquer tous les dysfonctionnements que la modif a créés, ce que je suis en train de faire ;-)

**Comment by cborne** [comment]
je suis étonné d'être le seul à te l'avoir remonté par contre

**Comment by broncowdd** [comment]
La vache, je m'en sors pas: plein de problèmes en cascade à cause de la prise en compte de la variable upload_path (parfois incluse parfois pas...) et comme la version d'Oros est plus complexe, je galère un max... je reprends sa version de base pour voir...

**Comment by cborne** [comment]
Je t'épargne mes commentaires désagréables :D

**Comment by broncowdd** [comment]
Ok, le bug ne vient pas de mes modifs mais de la version d'Oros. Je le recontacte...

**Comment by broncowdd** [comment]
du coup, les commentaires désagréables seront pour lui XD

**Comment by Oros42** [comment]
J'ai été pas mal occupé ces derniers jours. Donc je regarde ça en détails à partir de lundi.
