### ISSUE TITLE
Comment ajouter un type de fichier ?

### ISSUE THREAD

**Issue by adrien80080** [broncowdd/BoZoN#32]
Bonjour,
avant tout je tenais à te remercier pour ce superbe script qui me permet de garder mes fichiers avec moi. J'ai néanmoins un soucis à l'upload de fichier .epub.

J'ai en effet : "Error !  Forbidden file format !"
Je comprend pas là que BoZon n'autorise pas l'upload de fichier ePub.

J'ai donc tenté de modifier la ligne 52 comme ceci :
<code>$behaviour['FILES_TO_RETURN']=/*array();*/array('jpg','jpeg','gif','png','pdf','swf','mp3','mp4','svg','epub');</code>
J'ai également ajouté une ligne (273) : 
<code>'epub' => 'application/epub+zip',</code>

J'ai rechargé la page, vidé le cache, redémarré le serveur web, mais rien n'y fait, j'ai toujours cette même erreur.

Je me tourne donc vers vous pour trouver une solution.
Merci d'avance !

**Comment by broncowdd** [comment]
Bonjour,
C'est curieux que les fichiers epub soient refusés, j'en ai uploadé sans
soucis...
http://bozon.warriordudimanche.net/?f=155fd6cd9e43f7
S'il y a un format interdit à l'upload, c'est dans le script
auto_dropzone qu'il est défini:
$default_config=array(
    'forbidden_filetypes'=>'php',

De quelle version de Bozon s'agit-il ?
Tiens-moi au courant ;-)

**Comment by adrien80080** [comment]
Bonjour,
il s'agit de BoZon v.1.7. Voici le contenu concerné, de auto_dropzone
<code>$phpini=ini_get_all();
$default_config=array(
    'forbidden_filetypes'=>'php',
    'use_style'=>false,                         // false if you're using a external css file
    'auto_refresh_after_upload'=>true,          // auto refresh page after uploading files (except on errors)
    'max_length'=>2048,                          // Mo (see php.ini if changes doesn't work [post_max_size / upload_max_filesize])
    'dropzone_text'=>e('Drop your files here or click to select a local file',false),
    'dropzone_id'=>'dropArea',
    'dropzone_class'=>'dropArea',
    'destination_filepath'=>$_SESSION['current_path'].'/',     // this can be an array like 'jpg'=>'upload/jpeg/' or a string 'destination/'
    'my_filepath'=>$_SERVER['SCRIPT_NAME'],
);</code>

**Comment by LilaTequila** [comment]
Hello,
Pour info j'ai testé chez moi, j'ai la même erreur.
Bozon v1.7

**Comment by broncowdd** [comment]
Si mon pc veut bien redémarrer, je regarde ça ce soir ;-)

**Comment by broncowdd** [comment]
Je viens de jeter un oeil et je pense que le problème vient des deux fonctions suivantes dans auto_dropzone.php:
``` 
       function filetype(filemime){
            var parts = filemime.split("/");
            return (parts[(parts.length-1)]);
        }
        function is_allowed(filemime){
            var r='php';
            m=filetype(filemime);
            if (m==''){return false;}
            if(r.indexOf(m)==-1){return true;}
            else{return false;}
        }
```
et en partuculier de m=filetype(filemime); qui doit renvoyer une chaîne vide et déboucher sur un return false.
Ce serait bien que j'aie un des fichiers posant problème pour tester chez moi en live...

**Comment by broncowdd** [comment]
Salut, 
essaie de changer la ligne 278 d'auto_dropzone 
```
            if (m==''){return true;}
```
Je pense que certains fichiers renvoient une chaine vide dans filetype() et du coup, is_allowed renvoie false...
Toutefois, ce n'est que provisoire...

**Comment by chatainsim** [comment]
J'ai aussi le problème avec la dernière version (commit 616586a).
Mais je n'ai pas testé le fix proposé ci dessus.

**Comment by broncowdd** [comment]
Oui, je n'ai pas intégré la «correction» aux commits, il faut changer la ligne à nouveau (l. 280 dans la version 1.7.4)
