### ISSUE TITLE
auto_restrict error: token folder is not writeable

### ISSUE THREAD

**Issue by juanito003** [broncowdd/BoZoN#36]
Bonjour,

Je viens de tester l'install et j'obtiens 2 fois le message d'erreur :
> auto_restrict error: token folder is not writeable
> auto_restrict error: token folder is not writeable

Pour l'un des 2, en cherchant dans le code, j'ai compris qu'il fallait créer un dossier `private` avec les permissions 777. Pour le 2ème, je sais pas. Peut-on ajouter dans le README ce qu'il faut faire à l'installation ?
J'utilise PHP 5.6

![admin.php](https://framapic.org/E5qSbMwjlNtv/pw4jy06g)

Merci

**Comment by broncowdd** [comment]
Ok, merci pour le retour ^^
Je vais vois pourquoi ça fait ça asap.

**Comment by broncowdd** [comment]
Normalement, ce doit être réglé.
