### ISSUE TITLE
Create a zip from a folder

### ISSUE THREAD

**Issue by aledeg** [broncowdd/BoZoN#38]
I think it could be nice to have a way to create a zip archive from a folder. It's easier to share a single file than a folder when you want to download it.
This way you can download a single file and unzip it locally instead of downloading file by file the content of the shared folder.

**Comment by cborne** [comment]
s'il te demande de pouvoir télécharger un répertoire en zip ça peut être 
sympa aussi. Oui tiens fais le.

**Comment by broncowdd** [comment]
c'était prévu ^^
I already have this on my todo ^^

**Comment by broncowdd** [comment]
http://projets.warriordudimanche.net/public/board/85ca5305cfdb9e340d26e05fbefa77972b3afa3de3eba753cf87976b1cc5

**Comment by aledeg** [comment]
:+1:

**Comment by broncowdd** [comment]
;-)
