### ISSUE TITLE
Upload alternatif

### ISSUE THREAD

**Issue by arnaudmm** [broncowdd/BoZoN#4]
Hello, sympa ce BoZoN, merci du partage :)

J'aime beaucoup le côté anonyme des urls et je me suis demandé si je pouvais détourner ton soft pour l'upload de mes screenshots (par screencloud).

Pour faire bref j'ai déposé des fichiers dans le dossier uploads, j'ai refresh l'interface d'admin et mes fichiers ne sont pas apparus.

Serait-il donc envisageable de pouvoir uploader des fichiers autrement que par ta page(js) pour pouvoir profiter de la vue 'admin' et de l'anonymisation des liens ?

**Comment by broncowdd** [comment]
Obsolete
