### ISSUE TITLE
 multiple users

### ISSUE THREAD

**Issue by simpleuser99** [broncowdd/BoZoN#42]
How can I create multiple users for bozon?

**Comment by aledeg** [comment]
I am pretty sure you cannot. But that would be a pretty neat feature.

**Comment by broncowdd** [comment]
Multiple users functions are not easy to add: It'll cause a lot of security problems to solve, access rights for each profile etc... 
All the bozon's security structure would change and we'll lose the kiss aspect.

The only «alternative» should be to make various copies of bozon in different folders, like:
www.myserver.com/user1
www.myserver.com/user2 etc...

**Comment by aledeg** [comment]
Too bad :sob:
