### ISSUE TITLE
php.ini setting max_upload_size isn't correctly handled if you set the value to be 1G instead of 1024M

### ISSUE THREAD

**Issue by nicanaca0** [broncowdd/BoZoN#46]
Seems that the core code doesn't try work out what the unit is so when I used 1G in my .ini it was interpreted as 1M so I had to set it as 1024M instead.

**Comment by broncowdd** [comment]
Ok, I work on this asap. Thanks ;-)

**Comment by minami-o** [comment]
Confirm this!
I had this set to 2G and could only upload up to 2M, whereas my own "home-made" upload solution worked perfectly well. ;)
Now set to 2048M, and working with BoZoN, too.
Keep it up!

**Comment by broncowdd** [comment]
This problem is now fixed.
