### ISSUE TITLE
affichage des noms longs

### ISSUE THREAD

**Issue by cborne** [broncowdd/BoZoN#48]
Les noms très longs ne s'affichent pas, un système d'infobulles quand on passe dessus serait le bienvenu et tronqué bien sûr pour que ça fasse moins sale

**Comment by broncowdd** [comment]
Bonne idée ^^ et bonne année ! \o/

**Comment by cborne** [comment]
bon ça y est t'as codé ?

10 janvier 2016 13:05 "Bronco"  a écrit:
	Bonne idée ^^ et bonne année ! o/

**Comment by broncowdd** [comment]
Non, mais bonne année à toi aussi !
J'ai ajouté les infos bulles sur la vue en icône et j'ai mis en height auto la vue en liste (le nom, même long, s'affiche donc entier)
