### ISSUE TITLE
1.7.2 n'affiche plus les fichiers

### ISSUE THREAD

**Issue by SimpleHomeUser** [broncowdd/BoZoN#50]
Bonjour,

Je viens d'upgrader vers la version 1.7.2 sur mon mutualisé ovh.
Et ca ne fonctionne plus du tout: les fichiers ne sont plus affichés.
Quand je clique sur le menu (en haut a gauche) il ne se passe rien.
Je peux uploader un fichier mais ensuite il m'affiche "erreur de rechargement de la liste"
Le fichier est bien sur le serveur mais n'est pas affiché.
J'ai mis les droits en 777 pour tous les fichiers et dossiers mais ca ne change rien.

Je ne sais pas trop quels détails donner pour aider a la comprehension du probleme.

J'ai la version 1.7.1 qui fonctionne en parrallele et il n'y a pas de probleme.

**Comment by broncowdd** [comment]
Ah ? je vais regarder de suite: merci !

**Comment by broncowdd** [comment]
Très curieux, je ne parviens pas à reproduire le bug...

**Comment by SimpleHomeUser** [comment]
Quel genre de données / log je pourrais te fournir pour aider ?
Dès que j'ai un peu de temps, je vais essayer de voir les différences entre les 2 versions et échanger les fichiers genre mettre admin.php d'une version sur l'autre ..
Bon ca risque d'être dans qq jours ...
En tout cas merci pour ta réactivité et pour ton travail.

**Comment by broncowdd** [comment]
De rien ;-) 
L'erreur apparaît dans la partie js d'auto_dropzone.php
        function reload_list(){
           //reload list
            var request = new XMLHttpRequest();
            request.open('GET', 'listfiles.php', true);
            target=document.getElementById('liste');
            request.onload = function() {
            if (request.status >= 200 && request.status < 400) {
                // Success!                        
                target.innerHTML= request.responseText;
              } else {
                target.innerHTML= 'erreur de rechargement de la liste'

              }
            };

            request.onerror = function() {
              // There was a connection error of some sort
            };

            request.send();
        }

Donc, c'est la requête vers listfiles.php qui ne se passe pas comme il faudrait.

**Comment by cborne** [comment]
Ah ben je vois qu'en 2016 on change rien à 2015, effectivement j'ai plus rien qui s'affiche avec la 1.7.3 :D

**Comment by cborne** [comment]
l'erreur pour être un peu plus sérieux :+1: 

[Sun Jan 10 15:15:33 2016] [error] [client 192.168.1.12] PHP Notice:  Undefined index: HTTP_ACCEPT_LANGUAGE in /srv/web/web/bozon/core/core.php on line 382, referer: http://cyrille.darktech.org/bozon/admin.php
[Sun Jan 10 15:15:33 2016] [error] [client 192.168.1.12] PHP Notice:  Undefined index: HTTP_ACCEPT_LANGUAGE in /srv/web/web/bozon/core/core.php on line 382, referer: http://cyrille.darktech.org/bozon/admin.php
[Sun Jan 10 15:15:33 2016] [error] [client 192.168.1.12] PHP Fatal error:  Can't use function return value in write context in /srv/web/web/bozon/listfiles.php on line 7, referer: http://cyrille.darktech.org/bozon/admin.php

**Comment by broncowdd** [comment]
Tiens teste avec cette modif dans listfiles.php : remplace la ligne 7 par
``` 
$sid=session_id();
if (empty($sid)){session_start();}
```


et dans core.php: remplace la fonction navigatorlanguage l 382 par cette version
```
	function navigatorLanguage(){
		if (!empty($_SERVER['HTTP_ACCEPT_LANGUAGE'])){
			$language = $_SERVER['HTTP_ACCEPT_LANGUAGE'];
			return $language{0}.$language{1};
		}else{return 'fr';}
	}
```

**Comment by cborne** [comment]
le premier problème est réglé pour le second : [Sun Jan 10 15:46:36 2016] [error] [client 192.168.1.12] PHP Fatal error: Cannot redeclare navigatorLanguage() (previously declared in /srv/web/web/bozon/core/core.php:381) in /srv/web/web/bozon/core/core.php on line 381

ce qui me fait un magnifique écran blanc

10 janvier 2016 15:39 "Bronco"  a écrit:
	Tiens teste avec cette modif dans listfiles.php : remplace la ligne 7 par

	$sid=session_id(); if (empty($sid)){session_start();} 

	et dans core.php: remplace la fonction navigatorlanguage l 382 par cette version

	 function navigatorLanguage(){ if (!empty($_SERVER['HTTP_ACCEPT_LANGUAGE'])){ $language = $_SERVER['HTTP_ACCEPT_LANGUAGE']; return $language{0}.$language{1}; }else{return 'fr';} }

**Comment by broncowdd** [comment]
Tu as bien REMPLACÉ la fonction navigatorLanguage dans le core.php ?

**Comment by cborne** [comment]
tu as de la chance. Bon maintenant je regarde sur le tel si c'est dégueulasse

10 janvier 2016 15:51 "Bronco"  a écrit:
	Tu as bien REMPLACÉ la fonction navigatorLanguage dans le core.php ?

**Comment by cborne** [comment]
tu as bien bossé, je suis fier de toi, article, backlink tout ça.

10 janvier 2016 15:51 "Bronco"  a écrit:
	Tu as bien REMPLACÉ la fonction navigatorLanguage dans le core.php ?

**Comment by broncowdd** [comment]
Merci chef, vous etes gentil, chef !  :-)

Le 10 janvier 2016 16:03:49 CET, Cyrille BORNE <notifications@github.com> a écrit :
>tu as bien bossé, je suis fier de toi, article, backlink tout ça.
>
>10 janvier 2016 15:51 "Bronco"  a écrit:
>	Tu as bien REMPLACÉ la fonction navigatorLanguage dans le core.php ?
>
>	—
>Reply to this email directly or view it on GitHub
>(https://github.com/broncowdd/BoZoN/issues/50#issuecomment-170354510).
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/broncowdd/BoZoN/issues/50#issuecomment-170357944

-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.

**Comment by cborne** [comment]
bon je crois que tu peux mettre à jour maintenant parce qu'il doit y avoir quelques personnes qui attendent peut être

10 janvier 2016 16:10 "Bronco"  a écrit:

Merci chef, vous etes gentil, chef ! :-)

Le 10 janvier 2016 16:03:49 CET, Cyrille BORNE  a écrit :
>tu as bien bossé, je suis fier de toi, article, backlink tout ça.
>
>10 janvier 2016 15:51 "Bronco" a écrit:
> Tu as bien REMPLACÉ la fonction navigatorLanguage dans le core.php ?
>
> —
>Reply to this email directly or view it on GitHub
>(https://github.com/broncowdd/BoZoN/issues/50#issuecomment-170354510 (https://github.com/broncowdd/BoZoN/issues/50#issuecomment-170354510)).
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/broncowdd/BoZoN/issues/50#issuecomment-170357944 (https://github.com/broncowdd/BoZoN/issues/50#issuecomment-170357944)

--
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.

**Comment by broncowdd** [comment]
C'est déjà committé :-)

Le 10 janvier 2016 16:12:16 CET, Cyrille BORNE <notifications@github.com> a écrit :
>bon je crois que tu peux mettre à jour maintenant parce qu'il doit y
>avoir quelques personnes qui attendent peut être
>
>10 janvier 2016 16:10 "Bronco"  a écrit:
>
>Merci chef, vous etes gentil, chef ! :-)
>
>Le 10 janvier 2016 16:03:49 CET, Cyrille BORNE  a écrit :
>>tu as bien bossé, je suis fier de toi, article, backlink tout ça.
>>
>>10 janvier 2016 15:51 "Bronco" a écrit:
>> Tu as bien REMPLACÉ la fonction navigatorLanguage dans le core.php ?
>>
>> —
>>Reply to this email directly or view it on GitHub
>>(https://github.com/broncowdd/BoZoN/issues/50#issuecomment-170354510
>(https://github.com/broncowdd/BoZoN/issues/50#issuecomment-170354510)).
>>
>>
>>---
>>Reply to this email directly or view it on GitHub:
>>https://github.com/broncowdd/BoZoN/issues/50#issuecomment-170357944
>(https://github.com/broncowdd/BoZoN/issues/50#issuecomment-170357944)
>
>--
>Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma
>brièveté.
>
>	—
>Reply to this email directly or view it on GitHub
>(https://github.com/broncowdd/BoZoN/issues/50#issuecomment-170358542).
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/broncowdd/BoZoN/issues/50#issuecomment-170358646

-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.

**Comment by cborne** [comment]
tu peux fermer le responsive pour ma part, et les info bulles, pour le reste faut attendre que copain réponde.

10 janvier 2016 16:19 "Bronco"  a écrit:

C'est déjà committé :-)

Le 10 janvier 2016 16:12:16 CET, Cyrille BORNE  a écrit :
>bon je crois que tu peux mettre à jour maintenant parce qu'il doit y
>avoir quelques personnes qui attendent peut être
>
>10 janvier 2016 16:10 "Bronco" a écrit:
>
>Merci chef, vous etes gentil, chef ! :-)
>
>Le 10 janvier 2016 16:03:49 CET, Cyrille BORNE a écrit :
>>tu as bien bossé, je suis fier de toi, article, backlink tout ça.
>>
>>10 janvier 2016 15:51 "Bronco" a écrit:
>> Tu as bien REMPLACÉ la fonction navigatorLanguage dans le core.php ?
>>
>> —
>>Reply to this email directly or view it on GitHub
>>(https://github.com/broncowdd/BoZoN/issues/50#issuecomment-170354510 (https://github.com/broncowdd/BoZoN/issues/50#issuecomment-170354510)
>(https://github.com/broncowdd/BoZoN/issues/50#issuecomment-170354510) (https://github.com/broncowdd/BoZoN/issues/50#issuecomment-170354510))).
>>
>>
>>---
>>Reply to this email directly or view it on GitHub:
>>https://github.com/broncowdd/BoZoN/issues/50#issuecomment-170357944 (https://github.com/broncowdd/BoZoN/issues/50#issuecomment-170357944)
>(https://github.com/broncowdd/BoZoN/issues/50#issuecomment-170357944 (https://github.com/broncowdd/BoZoN/issues/50#issuecomment-170357944))
>
>--
>Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma
>brièveté.
>
> —
>Reply to this email directly or view it on GitHub
>(https://github.com/broncowdd/BoZoN/issues/50#issuecomment-170358542 (https://github.com/broncowdd/BoZoN/issues/50#issuecomment-170358542)).
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/broncowdd/BoZoN/issues/50#issuecomment-170358646 (https://github.com/broncowdd/BoZoN/issues/50#issuecomment-170358646)

--
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.

**Comment by SimpleHomeUser** [comment]
Wahou quelle équipe ! 
Un donneur d'ordre, testeur fou. 
Un codeur hyper réactif. 
Bravo ! 

Ca marche nickel. 
Merci

**Comment by cborne** [comment]
Oui c'est un peu surprenant quand on n'est pas habitué, mais c'est assez efficace si on fait pas trop attention à ce qui se passe entre le bug et la résolution

10 janvier 2016 18:38 "SimpleHomeUser"  a écrit:
	Wahou quelle équipe !
Un donneur d'ordre, testeur fou.
Un codeur hyper réactif.
Bravo !

	Ca marche nickel.
Merci
