### ISSUE TITLE
Affichage des caractères accentués pour les fichiers

### ISSUE THREAD

**Issue by cborne** [broncowdd/BoZoN#51]
Je fais un upload ça marche pas, il s'affiche pas. Et pourtant les dossiers ça marche

**Comment by chatainsim** [comment]
Pas de problème avec les fichiers accentués pour ma part.
Un problème au niveau de la conf du serveur web peut-être ?

**Comment by broncowdd** [comment]
Normalement, ce problème devrait être réglé.

**Comment by cborne** [comment]
bon je regarderai et maintenant que j'ai appris que tu codais comme un amateur, je vais regarder plutôt deux fois qu'une :D

tu vas avoir de ces commit, BoZon c'est le projet qui fédère

12 janvier 2016 11:39 "Bronco"  a écrit:
	Normalement, ce problème devrait être réglé.

**Comment by broncowdd** [comment]
Hinhin :-D 

Le 12 janvier 2016 11:45:45 CET, Cyrille BORNE <notifications@github.com> a écrit :
>bon je regarderai et maintenant que j'ai appris que tu codais comme un
>amateur, je vais regarder plutôt deux fois qu'une :D
>
>tu vas avoir de ces commit, BoZon c'est le projet qui fédère
>
>12 janvier 2016 11:39 "Bronco"  a écrit:
>	Normalement, ce problème devrait être réglé.
>
>	—
>Reply to this email directly or view it on GitHub
>(https://github.com/broncowdd/BoZoN/issues/51#issuecomment-170870184).
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/broncowdd/BoZoN/issues/51#issuecomment-170871837

-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.

**Comment by cborne** [comment]
bon les caractères accentués toujours pas

**Comment by cborne** [comment]
quel amateur ce bronco, pardon j'avais oublié, c'est la nouvelle tendance ici :D

**Comment by broncowdd** [comment]
je regarde ça ;-)

**Comment by broncowdd** [comment]
En fait, j'ai implémenté une fonction de filtrage des caractères indésirables dans les noms de fichiers: les lettres accentuées y figurent.
Je teste pour voir si en les acceptant, il n'y a pas de soucis.

**Comment by broncowdd** [comment]
Ok, c'est fait: à la ligne 176 du core.php, j'ai changé la regex de la fonction en cause:
```
function only_alphanum_and_dot($string){return preg_replace('#[^éèàçâêûîôÉÈÇÀÂÊÛÎÔÁÚÍÓÑáúíóña-zA-Z0-9\. _]#','',$string);}
```
;-)

**Comment by cborne** [comment]
tu as fais un commit parce que là je surveille mon contrôle et même si je me laisserai bien séduire par une modification à la main, j'aimerai rester raisonnable. Un petit upload me gène moins.

13 janvier 2016 08:54 "Bronco"  a écrit:
	Ok, c'est fait: à la ligne 176 du core.php, j'ai changé la regex de la fonction en cause:

	function only_alphanum_and_dot($string){return preg_replace('#[^éèàçâêûîôÉÈÇÀÂÊÛÎÔÁÚÍÓÑáúíóña-zA-Z0-9. _]#','',$string);} 

	;-)

**Comment by cborne** [comment]
marche pas

**Comment by broncowdd** [comment]
J'ai commit entre temps, mais si tu pouvais être plus spécifique ^^

**Comment by cborne** [comment]
oh la vieille critique, monsieur réclame de la clarté maintenant, c'est eauland et ça rigueur qui te font tourner la tête. En fait je renomme un fichier qui s'appelle etiquette en étiquette, il me fait sauter le é pour écrire tiquette. Je peux difficilement faire mieux.

13 janvier 2016 19:43 "Bronco"  a écrit:
	J'ai commit entre temps, mais si tu pouvais être plus spécifique ^^

**Comment by broncowdd** [comment]
Non, mais LÀ c'est clair ^^ 
Tu es certain d'avoir la modif en question ?

**Comment by cborne** [comment]
bah comme je te le faisais remarquer ce matin en plein contrôle, j'étais pas chaud pour une modif à la main, ce soir j'ai pensé à toi et je me suis dit, bon cette faignasse a bien dû commiter dans la journée et j'ai vu que la dernière modif sur le core c'était ça. J'ai uppé y a trente minutes et voilà où nous en sommes, j'ai rien édité à la main.

13 janvier 2016 20:03 "Bronco"  a écrit:
	Non, mais LÀ c'est clair ^^
Tu es certain d'avoir la modif en question ?

**Comment by broncowdd** [comment]
Ben c'est curieux ça... Je viens de tester, ça marche de mon côté...
Ce que tu décris c'est le comportement de l'ancienne version, tu as vérifié la regex de la ligne 176 ?
ça doit être la version contenant les accents: [^éèàçâêûîôÉÈÇÀÂÊÛÎÔÁÚÍÓÑáúíóña-zA-Z0-9. _]

**Comment by cborne** [comment]
faut tout faire ici. T'aurais pas commité ça m'étonnerait qu'à moitié. Je vais manger et je te raconte tout ça

13 janvier 2016 20:10 "Bronco"  a écrit:
	Ben c'est curieux ça... Je viens de tester, ça marche de mon côté...
Ce que tu décris c'est le comportement de l'ancienne version, tu as vérifié la regex de la ligne 176 ?
ça doit être la version contenant les accents: [^éèàçâêûîôÉÈÇÀÂÊÛÎÔÁÚÍÓÑáúíóña-zA-Z0-9. _]

**Comment by broncowdd** [comment]
je viens de vérifier la version committée, c'est la bonne... :-P ^^
Bon app' , je vais faire pareil

**Comment by cborne** [comment]
bon je confirme que ça marche pas : tiquettes._5696ab01dad4c.odt
 
voilà comment il me le renomme. 

et comme c'est toi je suis allé te chercher ton erreur dans la log 

[Wed Jan 13 20:52:10 2016] [error] [client 192.168.1.12] PHP Warning:  rename(thumbs/tiquettes._5696aac4eccfc.odt,thumbs/\xc3\xa9tiquettes.odt) [<a href='function.rename'>function.rename</a>]: No such file or directory in /srv/web/web/bozon/admin.php on line 166, referer: http://cyrille.darktech.org/bozon/admin.php
[Wed Jan 13 20:52:33 2016] [error] [client 192.168.1.12] PHP Warning:  rename(thumbs/\xc3\xa9tiquettes.odt,thumbs/tiquettes._5696ab01dad4c.odt) [<a href='function.rename'>function.rename</a>]: No such file or directory in /srv/web/web/bozon/admin.php on line 166, referer: http://cyrille.darktech.org/bozon/admin.php

je sais pas ce que ça veut dire mais je pense que c'est certainement lié à ton amateurisme.

**Comment by cborne** [comment]
UP

**Comment by broncowdd** [comment]
T'es con ^^ 
Je regarde ça quand j'ai un moment.

Le 13 janvier 2016 20:55:55 CET, Cyrille BORNE <notifications@github.com> a écrit :
>bon je confirme que ça marche pas : tiquettes._5696ab01dad4c.odt
> 
>voilà comment il me le renomme. 
>
>et comme c'est toi je suis allé te chercher ton erreur dans la log 
>
>[Wed Jan 13 20:52:10 2016] [error] [client 192.168.1.12] PHP Warning: 
>rename(thumbs/tiquettes._5696aac4eccfc.odt,thumbs/\xc3\xa9tiquettes.odt)
>[<a href='function.rename'>function.rename</a>]: No such file or
>directory in /srv/web/web/bozon/admin.php on line 166, referer:
>http://cyrille.darktech.org/bozon/admin.php
>[Wed Jan 13 20:52:33 2016] [error] [client 192.168.1.12] PHP Warning: 
>rename(thumbs/\xc3\xa9tiquettes.odt,thumbs/tiquettes._5696ab01dad4c.odt)
>[<a href='function.rename'>function.rename</a>]: No such file or
>directory in /srv/web/web/bozon/admin.php on line 166, referer:
>http://cyrille.darktech.org/bozon/admin.php
>
>je sais pas ce que ça veut dire mais je pense que c'est certainement
>lié à ton amateurisme. 
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/broncowdd/BoZoN/issues/51#issuecomment-171414506

-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.

**Comment by broncowdd** [comment]
Ok, c'est le premier caractère accentué qui est perdu... je regarde ce que je peux faire.

**Comment by cborne** [comment]
quel amateur

16 janvier 2016 13:18 "Bronco"  a écrit:
	Ok, c'est le premier caractère accentué qui est perdu... je regarde ce que je peux faire.

**Comment by broncowdd** [comment]
HAHA... j'ai trouvé pis c'est pas de ma faute ^^ C'est la fonction basename() qui semble virer le premier caractère s'il est accentué !
Bon, ben yapuka.

**Comment by broncowdd** [comment]
http://stackoverflow.com/questions/32115609/basename-fail-when-file-name-start-by-an-accent la preuve ^^

**Comment by broncowdd** [comment]
Tu peux tester pour voir (en gros c'est le core.php/admin.php/index.php et listfiles.php qu'il faut mettre à jour)

**Comment by cborne** [comment]
je vais prendre une douche d'abord, monter le lit de gamin, parce qu'entre les cailloux, la peinture, et maintenant le montage but, je sens pas la rose.

16 janvier 2016 14:29 "Bronco"  a écrit:
	Tu peux tester pour voir (en gros c'est le core.php/admin.php/index.php et listfiles.php qu'il faut mettre à jour)

**Comment by broncowdd** [comment]
On a vraiment les mêmes vies ^^

**Comment by cborne** [comment]
nickel tu viens de faire exploser ma log d'erreur. Le résultat est simple, rien ne s'affiche

Sat Jan 16 19:52:17 2016] [error] [client 192.168.1.12] PHP Warning:  include(core/templates.php) [<a href='function.include'>function.include</a>]: failed to open stream: No such file or directory in /srv/web/web/bozon/core/core.php on line 64
[Sat Jan 16 19:52:17 2016] [error] [client 192.168.1.12] PHP Warning:  include() [<a href='function.include'>function.include</a>]: Failed opening 'core/templates.php' for inclusion (include_path='.:/usr/lib/php') in /srv/web/web/bozon/core/core.php on line 64
[Sat Jan 16 19:52:18 2016] [error] [client 192.168.1.12] PHP Notice:  Undefined variable: templates in /srv/web/web/bozon/listfiles.php on line 17
[Sat Jan 16 19:52:18 2016] [error] [client 192.168.1.12] PHP Notice:  Undefined variable: templates in /srv/web/web/bozon/listfiles.php on line 18
[Sat Jan 16 19:52:18 2016] [error] [client 192.168.1.12] PHP Notice:  Undefined variable: templates in /srv/web/web/bozon/listfiles.php on line 19
[Sat Jan 16 19:52:40 2016] [error] [client 192.168.1.12] PHP Warning:  include(core/templates.php) [<a href='function.include'>function.include</a>]: failed to open stream: No such file or directory in /srv/web/web/bozon/core/core.php on line 64
[Sat Jan 16 19:52:40 2016] [error] [client 192.168.1.12] PHP Warning:  include() [<a href='function.include'>function.include</a>]: Failed opening 'core/templates.php' for inclusion (include_path='.:/usr/lib/php') in /srv/web/web/bozon/core/core.php on line 64
[Sat Jan 16 19:52:41 2016] [error] [client 192.168.1.12] PHP Notice:  Undefined variable: templates in /srv/web/web/bozon/listfiles.php on line 17
[Sat Jan 16 19:52:41 2016] [error] [client 192.168.1.12] PHP Notice:  Undefined variable: templates in /srv/web/web/bozon/listfiles.php on line 18
[Sat Jan 16 19:52:41 2016] [error] [client 192.168.1.12] PHP Notice:  Undefined variable: templates in /srv/web/web/bozon/listfiles.php on line 19
[Sat Jan 16 19:52:58 2016] [error] [client 192.168.1.12] PHP Warning:  include(core/templates.php) [<a href='function.include'>function.include</a>]: failed to open stream: No such file or directory in /srv/web/web/bozon/core/core.php on line 64
[Sat Jan 16 19:52:58 2016] [error] [client 192.168.1.12] PHP Warning:  include() [<a href='function.include'>function.include</a>]: Failed opening 'core/templates.php' for inclusion (include_path='.:/usr/lib/php') in /srv/web/web/bozon/core/core.php on line 64
[Sat Jan 16 19:52:58 2016] [error] [client 192.168.1.12] PHP Notice:  Undefined variable: templates in /srv/web/web/bozon/listfiles.php on line 17
[Sat Jan 16 19:52:58 2016] [error] [client 192.168.1.12] PHP Notice:  Undefined variable: templates in /srv/web/web/bozon/listfiles.php on line 18
[Sat Jan 16 19:52:58 2016] [error] [client 192.168.1.12] PHP Notice:  Undefined variable: templates in /srv/web/web/bozon/listfiles.php on line 19
[Sat Jan 16 19:53:00 2016] [error] [client 192.168.1.12] PHP Warning:  include(core/templates.php) [<a href='function.include'>function.include</a>]: failed to open stream: No such file or directory in /srv/web/web/bozon/core/core.php on line 64, referer: http://cyrille.darktech.org/bozon/admin.php
[Sat Jan 16 19:53:00 2016] [error] [client 192.168.1.12] PHP Warning:  include() [<a href='function.include'>function.include</a>]: Failed opening 'core/templates.php' for inclusion (include_path='.:/usr/lib/php') in /srv/web/web/bozon/core/core.php on line 64, referer: http://cyrille.darktech.org/bozon/admin.php
[Sat Jan 16 19:53:00 2016] [error] [client 192.168.1.12] PHP Warning:  include(core/templates.php) [<a href='function.include'>function.include</a>]: failed to open stream: No such file or directory in /srv/web/web/bozon/core/core.php on line 64, referer: http://cyrille.darktech.org/bozon/admin.php
[Sat Jan 16 19:53:00 2016] [error] [client 192.168.1.12] PHP Warning:  include() [<a href='function.include'>function.include</a>]: Failed opening 'core/templates.php' for inclusion (include_path='.:/usr/lib/php') in /srv/web/web/bozon/core/core.php on line 64, referer: http://cyrille.darktech.org/bozon/admin.php
[Sat Jan 16 19:53:00 2016] [error] [client 192.168.1.12] PHP Notice:  Undefined variable: templates in /srv/web/web/bozon/listfiles.php on line 17, referer: http://cyrille.darktech.org/bozon/admin.php
[Sat Jan 16 19:53:00 2016] [error] [client 192.168.1.12] PHP Notice:  Undefined variable: templates in /srv/web/web/bozon/listfiles.php on line 18, referer: http://cyrille.darktech.org/bozon/admin.php
[Sat Jan 16 19:53:00 2016] [error] [client 192.168.1.12] PHP Notice:  Undefined variable: templates in /srv/web/web/bozon/listfiles.php on line 19, referer: http://cyrille.darktech.org/bozon/admin.php

**Comment by broncowdd** [comment]
Bon, alors là, c'est sans doute que j'avais modifié d'autres fichiers sur ma version avant de faire celle-là... je regarde ce soir et je répare, t'en fais pas ^^

**Comment by broncowdd** [comment]
Oui, c'est ça: my bad... c'est la modif des templates. Je corrige...

**Comment by cborne** [comment]
Pour m'en faire faudrait que je sois habitué à un travail super pro, tu vois, comme si ça avait un caractère exceptionnel. C'est pas comme si j'avais pas l'habitude qu'à chaque commit tu casses un truc. J'espère qu'eauland va intervenir dans ce fil pour te corriger.

16 janvier 2016 20:14 "Bronco"  a écrit:
	Bon, alors là, c'est sans doute que j'avais modifié d'autres fichiers sur ma version avant de faire celle-là... je regarde ce soir et je répare, t'en fais pas ^^

**Comment by broncowdd** [comment]
Bon, j'ai commit une version complète... 
Je jongle avec trois versions, ya des fois, je commence à y voir flou oO
C'était dû à la séparation des templates pour les mettre dans des fichiers html (suite à un commentaire d'eauland)... que je n'avais pas encore commité.

**Comment by cborne** [comment]
c'est la faute à eauland tout ça, il te stresse comme un inspecteur académique. Il l'est peut être d'ailleurs.

16 janvier 2016 20:24 "Bronco"  a écrit:
	Bon, j'ai commit une version complète...
Je jongle avec trois versions, ya des fois, je commence à y voir flou oO
C'était dû à la séparation des templates pour les mettre dans des fichiers html (suite à un commentaire d'eauland)... que je n'avais pas encore commité.

**Comment by cborne** [comment]
ça passe, je te le valide
