### ISSUE TITLE
Mise à jour 1.6.3 vers 1.7.3 : plus de fichiers

### ISSUE THREAD

**Issue by Draky50110** [broncowdd/BoZoN#52]
Hello

J'ai voulu mettre à jour ma version 1.6.3 en 1.7.3 en écrasant directement les fichiers mais à l'arrivée dans l'admin, les fichiers ont disparu.

Je ne veux pas perdre les ID en réuploadant tout correctement, y'a moyen de mettre à jour proprement @broncowdd ?

Merci :)

**Comment by broncowdd** [comment]
Normalement, les id ne devraient pas être écrasés en cas de mise à jour des fichiers de l'appli (à moins que tu n'écrases le fichier id.php dans private) et le contenu d'upload/ ne devrait pas être altéré... 
En tout cas, je n'ai pas constaté de problème dans mes phases de test...
La seule incompatibilité sera pour les id protégés par mot de passe, car j'ai dû modifier le système à cause d'un bug.

**Comment by Draky50110** [comment]
Je crois avoir vu un bout de solution.
Ma version de départ n'a pas id.php y'a juste un id.txt à la racine, pas de dossier private non plus.
Y'a eu une migration à un moment ?
Je pars de la 1.6.3 hein pas 1.7.
