### ISSUE TITLE
Erreur de suppression des fichiers - You need a valid token to do that, boy !

### ISSUE THREAD

**Issue by chatainsim** [broncowdd/BoZoN#53]
Bonjour,
En effectuant des tests pour les problèmes  d'accent, je me suis aperçu d'un bug.
J'upload un fichier et tout de suite après, je le supprime.
J'ai la fenêtre de confirmation qui apparait et lorsque je fais ok, j'obtiens le message d'erreur suivant:
```
You need a valid token to do that, boy !
```
En fait le Token n'est pas passé dans l'url.
Si je rafraîchi la page ou change l'affichage ou navigue dans les répertoires pour ensuite supprimer ce fichier, le problème n’apparaît pas.

**Comment by cborne** [comment]
j'ai eu le même problème j'ai dû faire un refresh pour avoir la suppression.

11 janvier 2016 10:39 "Simon"  a écrit:
	Bonjour,
En effectuant des tests pour les problèmes d'accent, je me suis aperçu d'un bug.
J'upload un fichier et tout de suite après, je le supprime.
J'ai la fenêtre de confirmation qui apparait et lorsque je fais ok, j'obtiens le message d'erreur suivant:

	You need a valid token to do that, boy ! 

	En fait le Token n'est pas passé dans l'url.
Si je rafraîchi la page ou change l'affichage ou navigue dans les répertoires pour ensuite supprimer ce fichier, le problème n’apparaît pas.

**Comment by broncowdd** [comment]
En effet, je regarde ça de suite. Merci.

**Comment by broncowdd** [comment]
Ok, j'ai trouvé d'où ça vient, j'ai modifié les templates pour corriger, en attendant des modifs plus profondes ( #57 ^^)
