### ISSUE TITLE
Image locked_big.png qui ne s'affiche pas

### ISSUE THREAD

**Issue by chatainsim** [broncowdd/BoZoN#54]
Bonjour,
Lorsque j’accède a un fichier protégé par mot de passe, l'image locked_big.png ne s'affiche pas.
Il cherche l'image dans ROOT/img et non dans ROOT/desing/default/img

**Comment by broncowdd** [comment]
En effet, je corrige. Merci encore ;-)

**Comment by chatainsim** [comment]
Je confirme, c'est corrigé.

Merci
