### ISSUE TITLE
Problème de protection par mot de passe

### ISSUE THREAD

**Issue by chatainsim** [broncowdd/BoZoN#55]
Bonjour,
Je viens de faire le test de protection par mot de passe.
Lorsque j'ai un fichier partagé avec un mot de passe et que j'en protège un autre avec le même mot de passe, le premier redevient non protégé et disparaît temporairement de l'affichage le temps de faire un refresh de la page ou de changer de page.
Le mot de passe étant utilisé dans l'url ceci explique cela. Mais est-il possible de modifier le code pour pouvoir partager plusieurs fichiers avec le même mot de passe ?

**Comment by broncowdd** [comment]
Oui, ce système de protection par mot de passe est de toutes façons un peu fragile ^^ (au départ, c'est une option bricolée à l'arrache pour voir si ça intéressait quelqu'un)
Il faudra que je bosse dessus pour l'améliorer un peu, ne serait-ce que de corriger ce problème et éviter l'apparition du mdp en clair dans l'url ^^

**Comment by broncowdd** [comment]
Bon, j'ai trouvé, je corrige ça ;-)

**Comment by broncowdd** [comment]
Ok, c'est fait: désormais, on peut mettre le même mot de passe sur plusieurs ressources.

**Comment by chatainsim** [comment]
Je viens de tester, ça fonctionne bien :+1: 

Merci !
