### ISSUE TITLE
Impossible de supprimer un répertoire

### ISSUE THREAD

**Issue by chatainsim** [broncowdd/BoZoN#56]
Un autre bug que je rencontre, c'est lors de la suppression d'un répertoire.
Impossible pour moi de les supprimer, j'obtiens cette erreur là dans les logs d'apache:
```
[Mon Jan 11 13:44:39 2016] [error] [client 193.57.249.6] PHP Notice:  Undefined variable: dir in /var/www/wet/bozon/core/core.php on line 204, referer: http://xxxx.fr/bozon/admin.php
[Mon Jan 11 13:44:39 2016] [error] [client 193.57.249.6] PHP Notice:  Undefined variable: dir in /var/www/wet/bozon/core/core.php on line 204, referer: http://xxxx.fr/bozon/admin.php
```
Et le répertoire ne se supprime pas.

**Comment by broncowdd** [comment]
Au temps pour moi, ça vient d'une erreur dans le nom de variable dans la fonction rrmdir: il faut remplacer $rrmdir par $dir. 
```
	function rrmdir($dir) { 
		# delete a folder and its content
	...
```

Merci !

**Comment by chatainsim** [comment]
Je confirme, ça fonctionne.
