### ISSUE TITLE
Write error on server

### ISSUE THREAD

**Issue by t0m4s** [broncowdd/BoZoN#58]
Salut,

je viens d'installer Bozon pour la première fois et quand j'essaye d'uploader un fichier j'ai systématiquement ce message d'erreur dans la boite de dialogue d'upload (l'upload progresse jusqu'à 100% et après le message apparait) : **Write error on server**.
PHP ne génère aucune erreur.

Ma configuration :
un rapsberry pi
kernel 4.1.13
serveur web = lighttpd/1.4.31 (ssl) - Build-Date: Mar 13 2014 05:17:02
php 5.4.45-0+deb7u2

Si quelqu'un a une idée sur l'origine du problème, merci de m'aiguiller :).

PS : indications que vous pouvez peut-être inclure dans le readme pour éviter que les utilisateurs ne fuient en étant bloqués à l'installation :
- il faut que le propriétaire du dossier dans lequel bozon est installé soit l'utilisateur qui fait tourner le serveur web
- si on ne peut pas changer le propriétaire du dossier, il faut créer les dossiers private et uploads à la main (et sans doute changer leurs droits pour qu'ils soient accessibles en écriture par le script).

**Comment by t0m4s** [comment]
Hum, deux minutes plus tard...

Le problème vient du fait que l'utilisateur www-data n'est pas autorisé à écrire dans /tmp.

Vais modifier ça.

**Comment by broncowdd** [comment]
Essaie de tester avec des droits plus restreints, pour voir...

**Comment by t0m4s** [comment]
Salut,

impossible d'assigner des droits plus restreints.
chmod 777 /tmp --> ok
sudo chmod o-w /tmp --> Write error on server

PS : j'ai un autre soucis, j'ouvre un nouveau ticket
