### ISSUE TITLE
Not Found  The requested URL /index.php was not found on this server. 

### ISSUE THREAD

**Issue by cborne** [broncowdd/BoZoN#6]
Bonjour :)

je viens de faire l'installation sur un serveur un peu sale et je pense que la configuration apache ou une variante doit y être pour quelque chose. Aucune url générée par bozon ne passe. Une idée ? 

Cyrille

**Comment by cborne** [comment]
je réponds partiellement à ma question, j'ai placé bozon dans un sous répertoire, et lui n'en tient pas compte

**Comment by cborne** [comment]
je réponds moi même à la question, j'ai déplacé le répertoire bozon dans ce sous répertoire et je pensais qu'il allait suivre tout seul au niveau de la configuration. Peut on définir le chemin pour le répertoire d'upload pendant qu'on est dans les chemins

**Comment by broncowdd** [comment]
Ha, oui, je mets ça dans la todo... 
merci ^^
