### ISSUE TITLE
Rafraîchissement de la liste de fichiers/répertoires après création d'un répertoire

### ISSUE THREAD

**Issue by chatainsim** [broncowdd/BoZoN#61]
Hello,

Un petit bug pas trop gênant mais que je reporte quand même parce que bon j'ai envie ;)
Lorsque je crée un nouveau répertoire, la liste des contenus se rafraîchit mais elle doit se faire après la création du répertoire car celui-ci n’apparaît pas il faut que je rafraîchisse la liste ou la page pour qu'il apparaisse.

Voilà voilà et merci pour ton bon boulot @broncowdd  :+1:

**Comment by broncowdd** [comment]
Merci ! Je regarde ça asap
