### ISSUE TITLE
V 2.0 alpha : fait ou en cours

### ISSUE THREAD

**Issue by broncowdd** [broncowdd/BoZoN#63]
Bon, petit message pour dire où j'en suis dans les changements proposés par eauland:

- j'ai séparé les templates dans des fichiers html à part (ils sont mis en variable et gérés par le script templates.php)
- j'ai déplacé les fichiers stats.php, admin.php, login.php dans le dossier contenant le theme 
- j'ai créé un fichier share.php qui se charge de gérer les requêtes de partage
- j'ai aéré le code en déplaçant d'autres parties dans des scripts à part (la gestion GET POST des commandes admin par exemple,)
- j'ai séparé les langues en fichiers individuels et ils se trouvent dans le dossier locale
- désormais, tout passe par la page index.php qui gère les demandes de page (admin/stat par ex) et les demandes de partage: les parties nécessaires au traitement demandé sont incluses depuis index.php selon les besoins et les autorisations nécessaires,
- j'ai épuré certains passages et repris certains bouts de code, ajouté certaines fonctions utiles
- j'ai corrigé quelques bugs

reste à faire: 
- le menu à repenser (mais j'ai mon idée ^^)
- la maquette à reprendre complètement: là je m'en ferai une simpliste et je passerai la main ;-)
- tester à fond pour voir si c'est stable

Certaines parties resteront dans le dossier core/ parce qu'elles me semblent critiques et que leur modification n'apporterait rien à l'appli... De toutes façons, si quelqu'un veut tout de même modifier ces fichiers, il les trouvera là, inutile de sous-entendre qu'on peut les tripoter sans risques en les plaçant dans templates/. 
(templates.php, share.php,core.php, listfiles.php, get/post data + les libs utilisées.)

Toutes ces modifs permettront de séparer plus avantageusement le php de la maquette afin de faciliter le travail de ceux qui veulent se faire leur propre thème.

Voilà, allez,  hop, j'y retourne.

**Comment by cborne** [comment]
formidable, je bosse pas demain, j'ai hâte de le crasher.
