### ISSUE TITLE
Problème de type mime

### ISSUE THREAD

**Issue by cborne** [broncowdd/BoZoN#7]
- Si je mets une vidéo en avi, il ne me lance pas le download et me le lit dans le navigateur
- Si je fais clic droit dessus enregistrer sous, il m'enregistre le fichier sous le nom de index.php. 

Si owncloud peut le faire, tu peux le faire !

**Comment by cborne** [comment]
ce qui nous ramène à ça : http://forum.webrankinfo.com/forcer-telechargement-fichier-pdf-t34768.html

**Comment by broncowdd** [comment]
Oui: je peux le faire !!! ^^
Au passage, à la ligne 57 du core.php, tu peux retirer l'avi des extensions à retourner, ce qui devrait résoudre le problème... (je teste pour être sûr ;-)
$behaviour['FILES_TO_RETURN']=array('jpg','jpeg','gif','png','pdf','swf','mp3','mp4','avi','svg');

**Comment by broncowdd** [comment]
Sinon, je pourrais ajouter une icône "télécharger" ce qui serait sans doute plus ergonomique...

**Comment by cborne** [comment]
pour ma part j'aurai tendance à dire que s'il s'agit d'un logiciel de 
gestion de fichiers, il ne doit en aucun cas ouvrir mais bien télécharger

**Comment by broncowdd** [comment]
Valable à la rigueur pour les vidéos/mp3 mais pour une image...
Et si on faisait plutôt une icône visualiser (l'action par défaut du lien serait le téléchargement et l'icône visualiser permettrait de voir le fichier si c'est possible dans le navigateur)... Qu'en penses-tu ?

**Comment by cborne** [comment]
ben pour l'image, j'aurai tendance à dire que si tu veux les voir, tu as 
des galeries minimalistes du genre minigal nano. Très important de 
rester dans le sujet je pense :D

**Comment by broncowdd** [comment]
Ben, pour ma part, j'ai pas mal utilisé bozon pour partager rapidement des photos et parfois elles se ressemblent beaucoup ^^ Je pense que je vais opter pour l'icône de visualisation ;-)

**Comment by Draky50110** [comment]
Je plussoie @cborne pour le kiss : bozon = télécharger, enfin je suppose.
Mais bonne idée les icônes :+1:

**Comment by cborne** [comment]
la correction de type mime n'a pas été faite sur la page d'accueil, on récupère le même problème sauf qu'il ouvre un texte dégueulasse

**Comment by cborne** [comment]
et se produit si on file le lien en direct

**Comment by broncowdd** [comment]
C'est quel type de fichier ?

**Comment by cborne** [comment]
mkv ou avi

**Comment by broncowdd** [comment]
Curieux, de mon côté le téléchargement se passe normalement ... quid ?

**Comment by cborne** [comment]
problème similaire avec Chromium, vivaldi.

**Comment by cborne** [comment]
et même chose pour un collègue avec IE, Firefox sous Windows, Opera

**Comment by broncowdd** [comment]
Quand on utilise le lien de partage vers un fichier vidéo, il affiche du texte à la place, c'est ça ?

**Comment by cborne** [comment]
pas que la vidéo, tout fichier qui provient d'un lien de partage 
extérieur à la page admin

**Comment by broncowdd** [comment]
ha oui, là c'est carrément zarb...

**Comment by broncowdd** [comment]
http://bozon.warriordudimanche.net/index.php?f=155b506954b8cf essaie celui-là pour voir.

**Comment by cborne** [comment]
ça passe

**Comment by broncowdd** [comment]
Ben alors là... ?!
De mon côté: test local, sur mon RPI, sur mon serveur distant... no problem...
Quid?!

**Comment by cborne** [comment]
essaie celui là : 
http://cyrille.darktech.org/bozon/index.php?f=155ba936901727

j'ai le problème quand j'essaie de le visualiser.

**Comment by broncowdd** [comment]
Ha oui, effectivement... 
On dirait un problème d'encodage...

**Comment by cborne** [comment]
alors j'ai un problème qui revient :

[Thu Jul 30 23:15:01 2015] [error] [client 192.168.1.10] PHP Warning:  
Cannot modify header information - headers already sent by (output 
started at /srv/web/web/bozon/index.php:20) in 
/srv/web/web/bozon/index.php on line 21

**Comment by broncowdd** [comment]
Haaaaa...
Là on va avancer ^^
Y a-t-il une erreur avant dans les logs ? (genre l'erreur précédente ?)

**Comment by cborne** [comment]
quand tu dis avant, tu veux dire quand ?

**Comment by cborne** [comment]
il manque la favicon au fait

**Comment by broncowdd** [comment]
La ligne juste avant...
En fait, il y a sans doute quelque chose qui produit une sortie à l'écran, comme une erreur, ce qui empêche la commande header de fonctionner, provoque une erreur de plus et brouille le format normal.

**Comment by cborne** [comment]
la séquence d'avant j'ai ça :

[Thu Jul 30 23:12:43 2015] [error] [client 192.168.1.10] PHP Warning:  
Cannot modify header information - headers already sent by (output 
started at /srv/web/web/bozon/index.php:25) in 
/srv/web/web/bozon/index.php on line 26
[Thu Jul 30 23:12:43 2015] [error] [client 192.168.1.10] PHP Warning:  
Cannot modify header information - headers already sent by (output 
started at /srv/web/web/bozon/index.php:25) in 
/srv/web/web/bozon/index.php on line 28
[Thu Jul 30 23:13:20 2015] [error] [client 192.168.1.10] PHP Warning:  
Cannot modify header information - headers already sent by (output 
started at /srv/web/web/bozon/index.php:25) in 
/srv/web/web/bozon/index.php on line 26
[Thu Jul 30 23:13:20 2015] [error] [client 192.168.1.10] PHP Warning:  
Cannot modify header information - headers already sent by (output 
started at /srv/web/web/bozon/index.php:25) in 
/srv/web/web/bozon/index.php on line 28
[Thu Jul 30 23:13:46 2015] [error] [client 192.168.1.10] PHP Warning:  
Cannot modify header information - headers already sent by (output 
started at /srv/web/web/bozon/index.php:20) in 
/srv/web/web/bozon/index.php on line 21
[Thu Jul 30 23:14:11 2015] [error] [client 192.168.1.10] PHP Warning:  
Cannot modify header information - headers already sent by (output 
started at /srv/web/web/bozon/index.php:20) in 
/srv/web/web/bozon/index.php on line 21

j'ai pas vu plus

**Comment by cborne** [comment]
question stupide pourquoi j'ai du :20 ou :25 qui apparait ?

Je viens de faire un test qui fonctionne dans l'admin, l'erreur

[Thu Jul 30 23:36:56 2015] [error] [client 192.168.1.10] PHP Warning:  
Cannot modify header information - headers already sent by (output 
started at /srv/web/web/bozon/index.php:20) in 
/srv/web/web/bozon/index.php on line 21

arrive quoi qu'il arrive

**Comment by cborne** [comment]
même chose sur le même lien quand ça ne marche pas

**Comment by broncowdd** [comment]
C'est curieusement la ligne contenant ob_end_flush(); ... 
T'as essayé de le virer (en commentant la ligne : //ob_end_flush();) ?

**Comment by cborne** [comment]
ça ne règle pas le problème :

- à l'intérieur dans l'admin, l'image va passer en visualisation, pour 
un fichier trop gros ça plante
- pour l'extérieur, un fichier trop gros ça plante, un fichier de type 
mime connu il essaie de lancer vlc, un type inconnu il remet tout en 
caractère comme s'il voulait l'interpréter.

A mon sens c'est pas un problème de la ligne mais d'interprétation des 
types mime

**Comment by cborne** [comment]
et d'ailleurs on retrouve l'ancienne erreur sur la mémoire et l'erreur 
sur le header

[Thu Jul 30 23:47:55 2015] [error] [client 192.168.1.10] PHP Fatal 
error:  Out of memory (allocated 786432) (tried to allocate 1467697153 
bytes) in /srv/web/web/bozon/index.php on line 22, referer: 
http://cyrille.darktech.org/bozon/admin.php
[Thu Jul 30 23:47:59 2015] [error] [client 192.168.1.10] PHP Fatal 
error:  Out of memory (allocated 786432) (tried to allocate 1466628097 
bytes) in /srv/web/web/bozon/index.php on line 22, referer: 
http://cyrille.darktech.org/bozon/admin.php
[Thu Jul 30 23:48:29 2015] [error] [client 192.168.1.10] PHP Warning:  
Cannot modify header information - headers already sent by (output 
started at /srv/web/web/bozon/index.php:25) in 
/srv/web/web/bozon/index.php on line 26, referer: 
http://cyrille.darktech.org/bozon/index.php?f=155b5167ac5250
[Thu Jul 30 23:48:29 2015] [error] [client 192.168.1.10] PHP Warning:  
Cannot modify header information - headers already sent by (output 
started at /srv/web/web/bozon/index.php:25) in 
/srv/web/web/bozon/index.php on line 28, referer: 
http://cyrille.darktech.org/bozon/index.php?f=155b5167ac5250
[Thu Jul 30 23:49:12 2015] [error] [client 192.168.1.10] PHP Warning:  
Cannot modify header information - headers already sent by (output 
started at /srv/web/web/bozon/index.php:25) in 
/srv/web/web/bozon/index.php on line 26, referer: 
http://cyrille.darktech.org/bozon/index.php?f=155b509ccf12f4
[Thu Jul 30 23:49:12 2015] [error] [client 192.168.1.10] PHP Warning:  
Cannot modify header information - headers already sent by (output 
started at /srv/web/web/bozon/index.php:25) in 
/srv/web/web/bozon/index.php on line 28,

**Comment by broncowdd** [comment]
Je pense que le type mime doit être le bon, mais qu'une erreur vient parasiter le contenu en empêchant la commande header d'envoyer les informations de type.
Essaie de commenter les lignes readfile... si une erreur est survenue avant, il y aura une chance de la voir... (j'y crois pas trop, elle apparaîtrait dans les logs)

**Comment by cborne** [comment]
l'absence de readfile me met un écran blanc dans la page publique ce qui 
prouve bien qu'il ne fait pas le même traitement que dans la page admin 
où j'ai une proposition de téléchargement d'un fichier vide

**Comment by broncowdd** [comment]
oui, je m'en doutais, j'espérais que ça laisserait apparaître une erreur...
Tu as quelle version de php ?

**Comment by cborne** [comment]
PHP 5.3.27 (cli) (built: May 21 2015 12:14:37)

Pour l'erreur avec ou sans le readfile j'ai le problème sur le header

**Comment by cborne** [comment]
en fait quand je regarde ce qu'il me propose pour le téléchargement, 
quel que soit le fichier, il me dit que c'est un fichier de type html et 
me propose de l'ouvrir avec mousepad. Et ça je parle dans l'admin. Dans 
la page publique il ne propose pas le téléchargement et interprète 
naturellement le fichier comme du html.

C'est donc quelque part quelqu'un qui comprend pas le type mime qu'on 
lui envoie ou il lui est mal envoyé

**Comment by broncowdd** [comment]
*Bronco s'arrache les derniers cheveux qu'il lui reste*

**Comment by cborne** [comment]
/Bronco viendra rejoindre le digne camp des chauves, la voie des vrais 
bonhommes/

**Comment by cborne** [comment]
dans ma grande générosité, je l'ai installé sur mon mutualisé et ça 
fonctionne, le type mime est bien reconnu.

Néanmoins et c'est ce qui me pose quand même problème et qu'il faut 
arranger avant de se poser la question de mon dédié. Si je clique sur un 
fichier type pdf sur une page publique, il ne cherche pas à le 
télécharger mais à l'ouvrir dans le navigateur. Si le type mime est 
inconnu, il tente le downloade sinon il veut l'ouvrir, idem bien sûr 
pour les images et les vidéos.

il faut donc appliquer le même traitement à l'extérieur ce qui 
globalement règlerait mon problème sauf pour la visualisation où il 
continuera de penser que c'est un html

**Comment by cborne** [comment]
5.5 pour le mutualisé

**Comment by broncowdd** [comment]
Je vais y réfléchir... pour l'heure ce sera dodo: mes loulous vont me réveiller sans aucune pitié demain ;-)

**Comment by cborne** [comment]
pas mieux

**Comment by cborne** [comment]
je pense qu'il te manque un ob_start quelque part

**Comment by cborne** [comment]
un ob_start en ligne 10 résout plus ou moins le problème, dans la partie 
admin les types mime sont bien reconnus mais il va saturer la mémoire de 
façon étrange.

Si je prends un fichier de moins de 1 giga et que je prends un gros 
derrière ça marche, si par contre après le gros, je reprends un autre 
gros, ça plante. Donc ça va te mettre sur la voie je pense

**Comment by broncowdd** [comment]
C'est vraiment curieux... il n'y a pas de raison objective pour tout ça.
Même le ob_start ne devrait pas résoudre le problème... seulement le remettre à plus tard.
J'ai pensé à un problème de la fonction _mime_content_type: une de ses versions pouvait éventuellement poser problème en fonction de la version de php, mais je les ai testées individuellement sans erreur...

Plus ça va plus j'ai le sentiment qu'il pourrait y avoir un problème d'encodage (ça fait souvent chmir en php, quand même)
Y a-t-il une configuration qui forcerait l'encodage en iso par exemple sur les serveurs pour lesquels bozon dysfonctionne ? 

Sinon, on peut essayer de forcer l'encodage dans le header envoyé, pour voir (sans trop y croire)
```
if (is_in($ext,'FILES_TO_ECHO')!==false){				
				echo '<pre>'.htmlspecialchars(file_get_contents($f)).'</pre>';
			}
			else if (is_in($ext,'FILES_TO_RETURN')!==false){
				ob_end_flush();
				header('Content-type: '.$type.'; charset=utf-8');
				header('Content-Transfer-Encoding: binary');
				header('Content-Length: '.filesize($f));
				readfile($f);
			}
			else{
				ob_end_flush();
				header('Content-type: '.$type);
				header('Content-Transfer-Encoding: binary');
				header('Content-Length: '.filesize($f));
				// lance le téléchargement des fichiers non affichables
				header('Content-Disposition: attachment; filename="'.basename($f).'"');
				readfile($f);				
			}
```

**Comment by cborne** [comment]
à partir de quelle ligne

**Comment by broncowdd** [comment]
Dans le test initial de la page index.php
```
	include('core.php');
	$tree=false;
	if (!empty($_GET['f'])){
		$f=id2file(strip_tags($_GET['f']));
		if ($f && is_file($f)){
			# file request => return file according to $behaviour var (see core.php)
			$type=_mime_content_type($f);
			$ext=strtolower(pathinfo($f,PATHINFO_EXTENSION));
			if (is_in($ext,'FILES_TO_ECHO')!==false){				
				echo '<pre>'.htmlspecialchars(file_get_contents($f)).'</pre>';
			}
			else if (is_in($ext,'FILES_TO_RETURN')!==false){
				ob_end_flush();
				header('Content-type: '.$type.'; charset=utf-8');
				header('Content-Transfer-Encoding: binary');
				header('Content-Length: '.filesize($f));
				readfile($f);
			}
			else{
				ob_end_flush();
				header('Content-type: '.$type);
				header('Content-Transfer-Encoding: binary');
				header('Content-Length: '.filesize($f));
				// lance le téléchargement des fichiers non affichables
				header('Content-Disposition: attachment; filename="'.basename($f).'"');
				readfile($f);				
			}
			exit();	
		}else if ($f && is_dir($f)){
			# folder request: return the folder & subfolders tree 
			$tree=tree($f);
		}
	}
```

**Comment by cborne** [comment]
pour ma part le problème vient de la ligne ob_end_flush

compte pas trop sur moi pour les tests cet après midi sortie famille. 
Par contre cherche du côté de l'obstart, toutes les syntaxes que j'ai 
vues sur le net disent qu'un ob_en s'accompagne d'un ob start

**Comment by cborne** [comment]
la modif a le mérite de faire largement accélerer le temps de "détection"

**Comment by cborne** [comment]
il passe toujours du html par contre

**Comment by broncowdd** [comment]
oui, c'est logique: le start commence la mise en tampon et le flush la termine et le vide.
Toutefois, ce qui posait problème avant était que sans le flush, les données semblaient mises en mémoire (qui saturait) au lieu d'être directement envoyées, d'où le flush...
Mais c'est pas normal pour autant ^^

Bonne balade ! (je vais aller en forêt aussi, besoin d'air frais ;-)

**Comment by cborne** [comment]
je signale tout de même qu'il passe toujours du html. Il faudrait aussi 
que tu appliques le même traitement sur les pages publiques c'est à dire 
que lorsqu'on clique dessus et que le type mime est connu, il le 
télécharge et ne tente pas de l'ouvrir ce qui contournerait le bug sauf 
dans le cas de la visualisation où il continuera à penser que c'était du 
html.

**Comment by broncowdd** [comment]
En fait, pour ce qui est de l'accès proprement dit au fichier, il n'y a pas réellement d'admin ou de public, c'est la page index qui s'en charge et qui décide du comportement à adopter en fonction du type de fichier (variable behaviour dans le core.php)
pour forcer le téléchargement de tous les fichiers, il suffit de remplacer
```
$behaviour['FILES_TO_RETURN']=array('jpg','jpeg','gif','png','pdf','swf','mp3','mp4','svg');
```
par 
```
$behaviour['FILES_TO_RETURN']=array();
```

**Comment by broncowdd** [comment]
Tu peux essayer cette version, c'est celle sur laquelle je bosse en ce moment (j'implémente la gestion des partages spéciaux)
http://bozon.warriordudimanche.net/index.php?f=155bb5cecb12ec
Les modifs sont faites dessus (téléchargement forcé de tous les fichiers, pas de visu)

**Comment by cborne** [comment]
en page publique, toujours pas de téléchargement forcé

**Comment by cborne** [comment]
malgré la modification de la ligne 60 dans le core.php il continue de vouloir lire le fichier qu'il considère toujours comme du php

**Comment by cborne** [comment]
et question idiote, remplacer la fonction readfile qui d'après le net est bourrée de soucis ?

**Comment by broncowdd** [comment]
Je ne vois pas trop par quoi remplacer readfile: cette fonction lit le fichier et l'envoie directement en sortie sans le passage par une variable, ce qui me semble décisif précisément pour éviter la saturation de la mémoire avec les gros fichiers. Or, il ne resterait que file_get_contents (-> variable) ou fopen/fread (idem) pour accéder aux fichiers.

J'ai bien pensé à modifier le header pour voir  comme dans la doc: http://php.net/manual/fr/function.readfile.php

```
$file = 'monkey.gif';

if (file_exists($file)) {
    header('Content-Description: File Transfer');
    header('Content-Type: application/octet-stream');
    header('Content-Disposition: attachment; filename='.basename($file));
    header('Expires: 0');
    header('Cache-Control: must-revalidate');
    header('Pragma: public');
    header('Content-Length: ' . filesize($file));
    readfile($file);
    exit;
}
``` 
mais sans possibilité pour moi de reproduire le bug, c'est très difficile :-/
Tu m'as dit que le problème était identique pour d'autres: quelle est leur config et version de php ?
Je vais essayer de mon côté sur d'autres serveurs, pour voir...

**Comment by cborne** [comment]
en fait j'écrivais que les gens qui accédaient à mon serveur 
rencontraient le même problème quel que soit le navigateur.

**Comment by broncowdd** [comment]
Ok, donc c'est logique, c'est un blème de serveur, pas de front...
Il doit y avoir une particularité sur ce serveur-là qui provoque ce comportement, reste à trouver quoi pour pouvoir le gérer...
Config / version / extensions installées / machine / accès etc... il doit y avoir UN truc qui justifie le bug...
Je teste sur free pour le moment, mais je suis dans la phase "corrige les blèmes préalables" ^^

**Comment by cborne** [comment]
et le fait que si je suis sur une page publique il continue de vouloir 
interpréter plutôt que de downloader, normal ?

**Comment by broncowdd** [comment]
Oui  si il y a un problème d'interprétation du header envoyé, ce qui peut arriver s'il est parasité d'une façon où d'une autre...
Et en fait, comme je te disais plus haut, l'accès public au fichier n'est pas différent de son accès de son accès admin: si tu regardes le lien vers le fichier dans la partie admin, c'est bien celui qui fait appel à la page index.php. 
Le comportement face au fichier est censé être régi par la variable $behaviour (que je comptais mettre en page de config plus tard), mais ça semble être un problème malgré tout (toujours, sans doute, ce bug dans l'interprétation du header).

Index.php:
soit c'est un fichier à afficher comme du texte, dans ce cas on l'echo après sécurisation:
``` 
			if (is_in($ext,'FILES_TO_ECHO')!==false){				
				echo '<pre>'.htmlspecialchars(file_get_contents($f)).'</pre>';
			}
```
soit c'est un fichier à renvoyer dans le navigateur parce que celui-ci peut les interpréter directement (images, vidéos etc): on les envoie au navigateur sans rediriger pour éviter que le user ne connaisse le chemin sur le serveur, donc il faut passer par header/type mime/readfile

```
			else if (is_in($ext,'FILES_TO_RETURN')!==false){
				ob_end_flush();
				header('Content-type: '.$type.'; charset=utf-8');
				header('Content-Transfer-Encoding: binary');
				header('Content-Length: '.filesize($f));
				readfile($f);
			}
```

soit c'est un autre type de fichier, non interprétable par le navigateur, c'est donc un fichier à télécharger: on force le téléchargement via le header
```
			else{
				ob_end_flush();
				header('Content-type: '.$type);
				header('Content-Transfer-Encoding: binary');
				header('Content-Length: '.filesize($f));
				// lance le téléchargement des fichiers non affichables
				header('Content-Disposition: attachment; filename="'.basename($f).'"');
				readfile($f);				
			}	
```
Dans cette dernière option, on pourrait essayer une redirection simple vers le fichier pour voir si le navigateur affiche le chemin (qu'on voudrait cacher). Mais c'est peu satisfaisant: on n'aurait pas compris le POURQUOI ^^

**Comment by cborne** [comment]
ah ah ah j'ai trouvé l'erreur, j'ai fait sauter des espaces après des 
<?php, ça commence au premier.

réponse ici : 
http://stackoverflow.com/questions/8028957/how-to-fix-headers-already-sent-error-in-php

quelle bronca dans le code de Bronco. :D

**Comment by broncowdd** [comment]
ARGH !!!! Mais ça j'y ai pensé moi-même ! Mais je pensais que tu utilisais les versions directement, sans modifs ! x_x *Bronco décède dans un râle pitoyable*

**Comment by broncowdd** [comment]
Mais j'aime autant, c'est une erreur COMPREHENSIBLE XD

**Comment by cborne** [comment]
l'erreur est dans le code initial

**Comment by cborne** [comment]
je confirme, dans le master sur github, dès le début, y a un espace, 
donc c'est un bug qui ne vient pas de mes modifs :D

**Comment by broncowdd** [comment]
Normalement, ce sont les espaces AVANT les balises <?php qui posent probème:
En effet, si il y a un espace ou tout autre type de caractère hors des balises php, il est envoyé au navigateur et php a donc déjà envoyé les headers qui sont donc impossibles à modifier...
je regarde...

**Comment by cborne** [comment]
et je veux mon nom dans le changelog :D

parce qu'après effectivement ça change tout, ça passe aussi sur la page 
"principale"

**Comment by broncowdd** [comment]
d'ailleurs c'est pour la même raison qu'une erreur de php avant la commande header provoque le même effet en affichant un message d'erreur.
Tu me copies l'endroit modifié, pour voir ?
(pour le changelog, pas de soucis ;-)

**Comment by cborne** [comment]
attends j'ai encore le bug :D

**Comment by cborne** [comment]
et je rajoute que dans la configuration php si on a output_buffering = 
4096 décommenté ça passe pas

Correction après le premier <?php et avant le footer



<?php
     /**
     * BoZoN user part:
     * simply handles the get link.
     * @author: Bronco (bronco@warriordudimanche.net)
     **/


/* tester

         En fait, pour ce qui est de l'accès proprement dit au fichier, 
il n'y a pas réellement d'admin ou de public, c'est la page index qui 
s'en charge et qui décide du comportement à adopter en fonction du type 
de fichier (variable behaviour dans le core.php)
pour forcer le téléchargement de tous les fichiers, il suffit de 
supprimer le
*/


     include('core.php');
     $tree=false;
     if (!empty($_GET['f'])){
         $f=id2file(strip_tags($_GET['f']));
         if ($f && is_file($f)){
             # file request => return file according to $behaviour var 
(see core.php)
             $type=_mime_content_type($f);
             $ext=strtolower(pathinfo($f,PATHINFO_EXTENSION));

             if (is_in($ext,'FILES_TO_ECHO')!==false){
                 echo 
'<pre>'.htmlspecialchars(file_get_contents($f)).'</pre>';
             }
             else if (is_in($ext,'FILES_TO_RETURN')!==false){
                 ob_end_flush();
                 header('Content-type: '.$type.'; charset=utf-8');
                 header('Content-Transfer-Encoding: binary');
                 header('Content-Length: '.filesize($f));
                 readfile($f);
             }
             else{
                 ob_end_flush();
                 header('Content-type: '.$type);
                 header('Content-Transfer-Encoding: binary');
                 header('Content-Length: '.filesize($f));
                 // lance le téléchargement des fichiers non affichables
                 header('Content-Disposition: attachment; 
filename="'.basename($f).'"');
                 readfile($f);
             }
             exit();
         }else if ($f && is_dir($f)){
             # folder request: return the folder & subfolders tree
             $tree=tree($f);
         }
     }
?>
<head>
     <title>BoZoN: <?php e('Drag, drop, share.');?></title>
     <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
     <meta charset="utf-8" />
     <link rel="shortcut icon" type="/image/png" href="img/bozonlogo2.png">
     <link rel="stylesheet" type="text/css" href="style.css">

</head>
<body class="index">
<header>
     <div class="overlay">
         <p class="logo"></p>
         <div style="clear:both"></div>
     </div>
</header>
<?php
     if ($tree){
         completeID($tree);
         draw_tree($tree);

     }else{
?>

<?php }
?>
     <footer>
         Bozon v<?php echo VERSION;?> - <a 
href="http://warriordudimanche.net">WDD</a><br/><a 
href="https://github.com/broncowdd/BoZoN" class="github" title="<?php 
e('fork me on github');?>">&nbsp;</a>
     </footer>
</body>

**Comment by broncowdd** [comment]
Nan mais un espace de plus ou de moins APRES le <?php ça ne doit rien changer... oO

**Comment by cborne** [comment]
dans les recherches sur le fameux message d'erreur sur le header, tout 
dirige vers les espaces et la ligne du buffer dans les causes

**Comment by broncowdd** [comment]
Ben oui, les espaces avant <?php, après ?> ou entre ?> et <?php, car ce sont des caractères non interprétés par php et donc envoyés au navigateur... 

Les espaces à l'intérieur des balises php sont interprétés et ne conduisent pas à des sorties dans le navigateur (en dehors des echo, exit, var_dump, print_r, messages d'erreur etc...)

**Comment by cborne** [comment]
je pense que le flush n'a plus d'intérêt à partir du moment où j'ai 
modifié le php.ini

**Comment by cborne** [comment]
j'ai ça désormais qui traine : [Sat Aug 01 11:03:50 2015] [error] 
[client 192.168.1.10] PHP Notice:  ob_end_flush() [<a 
href='ref.outcontrol'>ref.outcontrol</a>]: failed to delete and flush 
buffer. No buffer to delete or flush in /srv/web/web/bozon/index.php on 
line 36,

la suppression de l'ob_end_flux résout comme on peut s'en douter le 
problème et le téléchargement passe quelle que soit la taille du fichier 
si bien qu'il s'agissait du problème de la configuration du php.ini et 
du output buffering

**Comment by broncowdd** [comment]
oui: de toutes façons ça m'a toujours paru inutile, vu qu'il n'y avait aucune mise en tampon dans mon code... autant le virer.
