### ISSUE TITLE
Problème installation

### ISSUE THREAD

**Issue by Coolmicro** [broncowdd/BoZoN#70]
Bonjour,
Lors de l'installation, quand je vais sur : index.php?p=admin, j'obtiens le message :
Cannot modify header information - headers already sent by (output started at /home/var/www/private/bozon/templates/default/header.php:5) in /home/var/www/private/bozon/core/auto_restrict.php on line 105
et je sus incapable de comprendre le problème (pas très doué en php :D)
(serveur nginx - php 5.4.45 - j'ai quelques petits sites sur ce serveur qui fonctionnent sans problème)
Merci d'avance si vous pouvez consacrer quelques minutes pour répondre
Cordialement

**Comment by broncowdd** [comment]
Je regarde asap, merci ^^

**Comment by broncowdd** [comment]
Je viens de modifier le fichier core/auto_restrict.php pour éviter cette erreur.
J'espère que ça résoudra le problème (en effet, je n'ai pas l'erreur chez moi :-/)
Tenez-moi au courant ;-)

**Comment by Coolmicro** [comment]
Bonjour,
Grand merci pour la réactivité. Plus d'erreur, ça fonctionne.
Je m'en vais maintenant tester tout ça.
Cordialement
