### ISSUE TITLE
Lien de partage : mauvais URL sous-répertoire

### ISSUE THREAD

**Issue by Draky50110** [broncowdd/BoZoN#71]
Hello.

J'ai bozon dans www.domaine.com/bozon
Je partage un dossier.
L'URL donné par bozon : www.domaine.com?f=xxxxx

Manque le sous-répertoire + /index.php

**Comment by cborne** [comment]
C'est le même bug qu'on a encore sur le flux RSS, je pense que tu as 
oublié de remettre la correction

**Comment by broncowdd** [comment]
je regarde asap.
Pour le sous-répertoire, c'est super ch... j'arrive pas à faire une fonction qui fonctionne en local ET en distant sur un nom de domaine ET en distant dans un sous-répertoire... Je vais trouver une solution ^^

**Comment by broncowdd** [comment]
Je viens de commit un correctif du fichier core.php, ça devrait marcher.

**Comment by Draky50110** [comment]
Pas de changements.
Par contre, je fais un glisser-déposer depuis l'explorateur de fichiers et au lieu d'avoir les barres vertes assez fines j'ai des grosses barres vertes et le texte n'importe comment dedans.

**Comment by broncowdd** [comment]
Quid ?! tu as une capture ?

**Comment by broncowdd** [comment]
pour voir le changement, il faut se déconnecter et se reconnecter (reset de session)

**Comment by Draky50110** [comment]
Ouf, c'est réglé :)
