### ISSUE TITLE
[question] Changement du mot de passe

### ISSUE THREAD

**Issue by Pafzedog** [broncowdd/BoZoN#74]
Salut,

J'ai donc installé ma première instance de BoZoN et "j'm'ai gourré" en tapant mon mot de passe ^^
Donc bon, mon navigateur s'est gentiment souvenu de ce dernier et je l'en remercie mais j'ai pas vu où on pouvait le modifier si c'est possible.
D'ailleurs pour éviter ce genre de bourde à d'autres boulets comme moi, peut-être que ce serait intéressant de double checker celui-ci à la création au cas où ils aient pas un navigateur aussi sympa que le mien ;)

**Comment by broncowdd** [comment]
Oui, en effet, j'y ai pensé sans avoir le temps de m'y mettre: un double check et la possibilité de le changer ne seraient pas du luxe ! (Au passage, j'ai maintes fois fait partie des boulets ! ^^) hop TODO

Le 31 janvier 2016 23:39:18 CET, Pafzedog <notifications@github.com> a écrit :
>Salut,
>
>J'ai donc installé ma première instance de BoZoN et "j'm'ai gourré" en
>tapant mon mot de passe ^^
>Donc bon, mon navigateur s'est gentiment souvenu de ce dernier et je
>l'en remercie mais j'ai pas vu où on pouvait le modifier si c'est
>possible
>D'ailleurs pour éviter ce genre de bourde à d'autres boulets comme moi,
>peut-être que ce serait intéressant de double checker celui-ci à la
>création au cas où ils aient pas un navigateur aussi sympa que le mien
>;)
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/broncowdd/BoZoN/issues/74

-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.

**Comment by Pafzedog** [comment]
Sinon à la mano, y-a-t-il une manip pour reset mon mot de passe du coup ?

**Comment by broncowdd** [comment]
oui, il suffit de supprimer le fichier private/auto_restrict_users.php :
il te proposera de refaire une inscription et il suffira alors de
reprendre le même login et de mettre le mdp...

**Comment by Pafzedog** [comment]
le top !
merci bien
