### ISSUE TITLE
[ergonomie] fonction "déplacer" avec les autres fonctions de gestion de fichier

### ISSUE THREAD

**Issue by Pafzedog** [broncowdd/BoZoN#76]
Je comprend pas pourquoi la fonction "déplacer" est sur un onglet à part, je la verrais bien avec les autres fonctions "supprimer",'renommer", "obtenir le lien" et "télécharger", ça me semblerait plus clair.

Le fait aussi que les actions pour déplacer un dossier et  un fichier soient différentes,  je dois être un peu à l'ouest mais j'ai mis un moment à comprendre (ok j'ai pas lu les indications en gros juste en dessous ...)

A vrai dire même la gestion des liens, je la verrais bien sur le même onglet ^^ 
d'accord ça ferait un peu chargé(surtout pour la version mobile) mais il y aurait peut-être moyen de faire un genre de sous-menu qui se déploie au clic ou au survol ?

Bon, vous l'avez compris, j'aime pas les onglets ^^' (désolé)

**Comment by broncowdd** [comment]
La multiplication des fonctions a demandé un grand nombre de boutons et
donc, comme tu le dis, une surcharge indéniable: impossible de tout
mettre au même endroit...
Le coup du sous-menu m'est bien venu à l'esprit, mais pas de survol sur
smartphone/tablette...

Ceci dit, il faudra vraiment que je fasse une doc/wiki... un jour. ^^

**Comment by broncowdd** [comment]
J'ai commit une version qui supprime le mode déplacement et l'intègre au mode fichiers ;-)

**Comment by Pafzedog** [comment]
C'est de toute beauté !
et en bonus la fonction déplacer unifiée entre les fichiers et les dossiers :)

**Comment by broncowdd** [comment]
merci ;-)
