### ISSUE TITLE
HTTP 403 for /core/qr.js

### ISSUE THREAD

**Issue by ankerfest** [broncowdd/BoZoN#77]
Hi,
what is the purpose of having the access control directive `deny from all` in /core/.htaccess? That results for me in a 403 status code (forbidden) when the browser trys to GET /core/qr.js. Am I doing something wrong?

Thanks

**Comment by broncowdd** [comment]
Nope, that's on me ^^ Don't worry I'll fix the bug asap. Thanks ;-)

**Comment by broncowdd** [comment]
Ok, You only have to change the .htaccess file in core/ :  
```
Order Allow,Deny
<FilesMatch "qr.js">
Allow from all
</FilesMatch>
```
That's all ^^

**Comment by ankerfest** [comment]
Ok thank you,
I'd say that second JS file /sorttable.js will also be denied if the browser requests it. Something like
```
Order Allow,Deny
<FilesMatch "\.(js)$">
Allow from all
</FilesMatch>
```
would do the trick, I guess. Great work btw.

**Comment by broncowdd** [comment]
You're right, I change it, thx
