### ISSUE TITLE
512 Mo ?

### ISSUE THREAD

**Issue by cborne** [broncowdd/BoZoN#8]
j'ai bougé toutes les variables dans le php.ini et je me retrouve avec une limitation à 512 Mo, si je regarde dans le code directement sur la page je vois bien un 512 dedans ... Tu le prends où ce 512 ?

**Comment by broncowdd** [comment]
C'est une valeur arbitraire ;-)

A la ligne 62 d'auto_dropzone tu peux fixer ta propre limite de taille:
    'max_length'=>512,    
Si le php.ini est inférieur, c'est sa valeur qui sera utilisée, s'il est supérieur, c'est celle de la config d'auto_dropzone qui prévaudra.

Si tu veux, tu peux augmenter cette valeur pour mettre la même que celle de ton php.ini

**Comment by cborne** [comment]
et pourquoi tu le prends pas dans php.ini ?

**Comment by broncowdd** [comment]
C'est ce que fait auto_dropzone: il teste le php.ini pour sa propre config.
Cette option est destinée à ceux qui n'auraient pas la main sur le php.ini (ou qui ne sauraient pas faire) et qui voudraient réduire la taille des fichiers uploadables sur leur espace ^^

**Comment by cborne** [comment]
sauf que j'ai dans mon php.ini du 2048 et que je n'imaginais pas 
modifier ailleurs pour avoir du 2048 partout

**Comment by broncowdd** [comment]
je pense mettre ce paramétrage dans une future page de config, qui proposera par défaut la valeur du php.ini.

**Comment by cborne** [comment]
perfect !

**Comment by cborne** [comment]
et je me retrouve avec un PHP Fatal error:  Out of memory (allocated 524288) qui nous renvoie aussi à un 512Mo, c'est le même ?

**Comment by broncowdd** [comment]
Non, normalement ça ne doit pas venir de là... c'est au moment de l'upload ?

**Comment by cborne** [comment]
c'est plus gênant c'est au moment d'une tentative de téléchargement de 
fichiers de plus 1 Go. Le problème c'est que ça passe sur un fichier de 
700, et si ce même fichier je tente de le télécharger j'ai 0 octet. Ma 
memory limit est à 2048, je cherche encore.

**Comment by broncowdd** [comment]
Etrange... que ça gatouille à l'upload, à la rigueur... mais au download ?!
Le problème ne s'est jamais posé pour moi: vu mon débit au charbon de bois à la maison, il ne me serait jamais venu à l'idée d'envoyer des fichiers d'un giga XD

**Comment by cborne** [comment]
en fait j'uploade sur mon serveur à domicile, donc je ne vais pas très 
loin. Ces fichiers passent sans problème avec owncloud sur la même 
machine. As tu la possibilité de le tester via une machine virtuelle 
éventuellement ?

**Comment by broncowdd** [comment]
Il faudrait que je réinstalle, mais c'est faisable... 
Donc, tu dépose un fichier d'un giga et le téléchargement se fait jusqu'à un certain point ... 
La limite de mémoire vive allouée à php pourrait être un problème, mais je ne vois pas pourquoi (aucune variable de grande taille n'est stockée en ram...)

Le fichier est uploadé jusqu'au bour ?
Via FTP, le fichier est bien présent dans le dossier ? sa taille est-elle correcte ?

**Comment by broncowdd** [comment]
J'ai une elementaryOS qui traîne, je vais l'installer en virtuel, je configure et je teste.

**Comment by cborne** [comment]
non, je balance par ftp dans le répertoire qui va bien, j'ai une erreur 
directement du type :

[Sun Jul 26 18:10:57 2015] [error] PHP Fatal error:  Out of memory 
(allocated 524288) (tried to allocate 1466628097 bytes) in 
/srv/web/web/bozon/index.php on line 21, referer: 
http://192.168.1.x/bozon/admin.php

ce qui m'étonne c'est que dans mon php.ini j'ai du 2048M

cela se traduit par un fichier à 0 octets si je tente de le télécharger 
par clic droit et une page blanche si je clique dessus

**Comment by cborne** [comment]
je complète. Lorsque le fichier est trop gros et que le type mime est 
inconnu si je clique dessus il me renvoie "fichier non trouvé" dans le 
navigateur.

Je m'étonne aussi qu'il mouline autant lorsqu'on lance un downloade, on 
dirait qu'il réfléchit, mais on sait pas trop pour quoi faire.

**Comment by broncowdd** [comment]
Haaaaaa.... ok.
La taille précisée dans le php.ini ne concerne que la taille limite des fichiers uploadables par un formulaire html. Donc dans ce cas, rien à voir.
Par contre, php essaie d'attribuer plus de mémoire que ce qui est à sa disposition... donc erreur.
Et il semble essayer d'attribuer une taille correspondant à celle du fichier envoyé...

Pour ce qui est du type mime inconnu, peut-être faudrait-il un type mime par défaut... quel est le fichier que tu cherches à uploader ?

**Comment by broncowdd** [comment]
C'est readfile qui fait planter le bouzin (l 21 d'index.php)
Il doit sans doute charger le fichier en mémoire AVANT de l'envoyer et là poufcétout...
Je réfléchis à une solution alternative.

**Comment by broncowdd** [comment]
doc de php: «To anyone that's had problems with Readfile() reading large files into memory the problem is not Readfile() itself, it's because you have output buffering on. Just turn off output buffering immediately before the call to Readfile(). Use something like ob_end_flush().»

pourtant, je n'utilise pas la bufferisation... quid ?!

**Comment by cborne** [comment]
le limit memory doit pas concerner que l'upload ?
pour le type mime inconnu c'était le mkv.

Je précise que si le mkv est plus petit que 1 Go, il downloade direct 
par contre il me rajoute au nom de fichier les noms des répertoires dans 
lesquels il est contenu dans mon exemple il me met 
uploads_Vidéos_Documentaires_ en plus pour le nom de fichier.

**Comment by cborne** [comment]
et pourquoi tu charges le fichier aussi ? :D

j'espère que tu apprécies le test même pas poussé :D

**Comment by broncowdd** [comment]
J'aime bien que les autres testent pour moi: j'ai toujours la flemme... j'aurais pu bosser chez microsoft ^^

Pour le nom, la nouvelle version devrait corriger le tir;

**Comment by cborne** [comment]
moi j'aime bien qu'on trouve la solution dans la minute, j'aurai pu être 
prof ... Hummm .... ^^

**Comment by cborne** [comment]
*Note*:

    *readfile()* ne présentera pas de problème mémoire, même lors de
    l'envoi de gros fichiers. Si vous rencontrez ce type de problème,
    assurez-vous que la mise en mémoire tampon de la sortie est
    désactivée avec la fonction ob_get_level()
    <http://php.net/manual/fr/function.ob-get-level.php>.

**Comment by broncowdd** [comment]
mouhouhaha ! XD

**Comment by broncowdd** [comment]
Oui, j'ai vu: c'est la même page ;-)

**Comment by broncowdd** [comment]
Pour tester si àa viendrait de ça (ce dont je doute vu que je ne vois pas ce que la bufferisation vient faire dans bozon ^^) on peut ajouter ça dans la page index.php (ligne 16)
```
			if (is_in($ext,'FILES_TO_ECHO')!==false){				
				echo '<pre>'.htmlspecialchars(file_get_contents($f)).'</pre>';
			}
			else if (is_in($ext,'FILES_TO_RETURN')!==false){
				ob_end_flush();
				header('Content-type: '.$type);
				readfile($f);
			}
			else{
				ob_end_flush();
				header('Content-type: '.$type);
				// lance le téléchargement des fichiers non affichables
				header('Content-Disposition: attachment; filename="'.$f.'"');
				readfile($f);				
			}
```

en gros, on ajoute un vidage/fermeture de la bufférisation  avec ob_end_flush();

Si tu peux, essaie, pour voir.

**Comment by broncowdd** [comment]
Je teste en ce moment sur mon RPI (j'avais oublié qu'il était là ^^) 
24 %

**Comment by cborne** [comment]
ça passe.

AH AH !!!!

**Comment by cborne** [comment]
bon va falloir sortir une version avec la gestion du mime, parce que je 
connais des gros lourds qui vont tenter de streamer des fichiers de 1.5 
Go depuis le serveur. Le réflexe c'est quand même de cliquer pour 
downloader, pas de chance ça se lit direct et quand c'est de la grosse 
vidéo ça met le serveur à genou.

1.4.1 s'impose.

**Comment by broncowdd** [comment]
Hinhin... oui ^^ 
J'ai déjà ajouté l'icône de visualisation (donc le lien télécharge par défaut)

**Comment by cborne** [comment]
même si ça corrige le problème, je m'étonne que ce soit aussi long que 
ça pour avoir le lien de téléchargement

**Comment by broncowdd** [comment]
je teste en ce moment (plein de conneries annexes à régler: php à installer, blèmes de config, blèmes de droits d'accès au fichiers: je sudo à mort ^^)

**Comment by cborne** [comment]
le côté 5 secondes avant l'ouverture du lien c'est pas bien. Ca veut 
dire que readfile doit continuer à faire quelque chose avant de tout lâcher

**Comment by broncowdd** [comment]
Alors, après plusieurs tests et galères diverses:
1- le problème de taille à l'upload peut aussi venir de la variable post_max_size, fixée par défault à 10Mo... si on uploade plus, ça peut poser des soucis.
2- de mon côté, pas de délai de téléchargement (mais j'ai testé en local): ça démarre direct.
3- j'ai découvert un bug que je pensais avoir déjà réglé depuis longtemps sous firefox (qui fait globalement chier dès qu'on fait du js) : quand on dépose un fichier dans la dropzone, il ouvre un nouvel onglet avec le fichier en question... tu confirmes ce bug ou c'est juste pour moi ?

**Comment by cborne** [comment]
je n'ai pas testé l'uploade puisqu'en fait je fais tout passer par le ftp
