### ISSUE TITLE
Problème de renommage de fichiers

### ISSUE THREAD

**Issue by wiltur** [broncowdd/BoZoN#80]
Bonjour,

J'upload un fichier nommé **mon-fichier.ext**

Si je veux le renommer en **mon-fichier01.ext** par exemple, le tiret disparaît et ça donne **monfichier01.ext**

**Comment by broncowdd** [comment]
Ha oui, c'est le filtrage de caractères qui est un peu trop zélé: je corrige ça rapidement, merci.

**Comment by broncowdd** [comment]
Voilà: normalement, ça doit marcher ;-)

**Comment by broncowdd** [comment]
il suffit de récupérer core.php

**Comment by wiltur** [comment]
Impeccable :)
