### ISSUE TITLE
[Bug ?]Perte du lien de partage

### ISSUE THREAD

**Issue by wiltur** [broncowdd/BoZoN#81]
Bonjour,

Est-il normal que le lien généré pour un fichier ne soit plus valable quand on déplace ce fichier dans un autre dossier ?
Peut-être est-ce dû à la façon dont les liens sont générés, mais il serait bien que les liens soient conservés quelque soit l'emplacement des fichiers. (enfin disons que pour mon usage ça me semble assez indispensable, car redonner des liens est compliqué, surtout quand on réorganise les dossiers, tous les liens par fichiers sont perdus)

**Comment by broncowdd** [comment]
Ha oui, je n'y avais pas pensé...
J'imagine que ce doit être possible: à l'origine, bozon réattribue un ID aux fichiers qui n'en possèdent pas dans le dossier courant (pour permettre les manipulations par FTP sans se taper l'attribution des ID à la main); quand on déplace un fichier, c'est ce système qui est activé.
Je pense qu'en faisant un changement dans la partie gérant le déplacement, ce doit être facile à faire.
Je me le note pour la prochaine version.
Merci pour ce retour.
