### ISSUE TITLE
Galerie : affichage sans réorientation exif alors que le fichier image est correctement tourné

### ISSUE THREAD

**Issue by Draky50110** [broncowdd/BoZoN#84]
Hello.

J'ai une galerie avec 3 images.
BoZon affiche les fichiers JPEG sans les tourner correctement dans la vue du dossier mais quand je clique sur une image, il la tourne correctement là (il se base sur l'EXIF ?).

Suggestion : vérifier au moins l'orientation à l'affichage du dossier.

Exemple : http://gilles.wittezaele.fr/bozon/index.php?f=156b8731412b42
La première image et la deuxième ne sont pas correctement affichées en galerie mais le fait de cliquer dessus les affiche individuellement et dans le bon sens.

**Comment by broncowdd** [comment]
Ha oui, c'est la génération de miniatures qui doit faire ça... À creuser... Merci !

Le 8 février 2016 12:02:33 CET, Gilles <notifications@github.com> a écrit :
>Hello
>
>J'ai une galerie avec 3 images
>BoZon affiche les fichiers JPEG sans les tourner correctement dans la
>vue du dossier mais quand je clique sur une image, il la tourne
>correctement là (il se base sur l'EXIF ?)
>
>Suggestion : vérifier au moins l'orientation à l'affichage du dossier
>
>Exemple : http://gilleswittezaelefr/bozon/indexphp?f=156b8731412b42
>La première image et la deuxième ne sont pas correctement affichées en
>galerie mais le fait de cliquer dessus les affiche individuellement et
>dans le bon sens
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/broncowdd/BoZoN/issues/84

-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.

**Comment by eauland** [comment]
Un merge a été fait mais un bug existe si une image n'a pas d'info exif apparemment.

**Comment by aledeg** [comment]
As tu une image sans exif que je puisse tester?

**Comment by eauland** [comment]
http://bozon.unelio.xyz/index.php?f=156ca0d506ee40

**Comment by aledeg** [comment]
Je viens de tester avec la dernière version de BoZon et je n'arrive pas à reproduire. Est ce que tu as fait quelque chose de particulier?

**Comment by eauland** [comment]
hmmm....

https://github.com/eauland/BoZoN-Fork

Peut-être une mauvaise implémentation ?

**Comment by aledeg** [comment]
J'ai fait un diff entre le fichier de ton fork et celui présent dans master et la seule différence c'est le retour chariot sur la dernière ligne.
Je ne vois pas ce que ça peut être

**Comment by eauland** [comment]
Bizarre j'ai plus le problème, peut être une erreur vu que je retouche les css/html de la galerie en ce moment...

**Comment by aledeg** [comment]
Tant mieux sinon je ne voyais pas d'où pouvait provenir le problème

**Comment by Draky50110** [comment]
Heu...
http://gilles.wittezaele.fr/bozon/index.php?f=156b8731412b42
Toujours mal orienté et en plus quand on clique sur la première, il ne redresse pas non plus l'image.
