### ISSUE TITLE
[BUG] Upload de gros fichiers

### ISSUE THREAD

**Issue by Arno0x** [broncowdd/BoZoN#86]
Salut,

J'ai un souci d'upload de fichiers lorsque ceux-ci sont trop gros.
Environnement de test:

- OS: OSX 10.9.5
- Browser: Firefox 43.0.4 et Chromium Version 46.0.2489.0 (64-bit)
- Limite d'upload est fixée à 200Mo dans mon php.ini.

L'upload de fichier de 200Ko et 700Ko fonctionne correctement. Mais l'upload d'un fichier de 5Mo cause le comportement suivant:
La barre de progression d'upload monte jusqu'entre 50% et 60% puis "saute" à 0% et recommence. Ça saute comme ça environ 2 ou 3 fois, avant d'abandonner, sans message d'erreur (la barre de progression disparait, c'est tout, et le fichier n'est pas uploadé).

Arno

**Comment by cborne** [comment]
une limitation quelconque sur le temps ?

**Comment by Arno0x** [comment]
Non, ça n'est pas ça mais tu m'as mis sur la piste. Je n'ai même pas pensé à regarder les logs... En fait c'était une limitation au niveau de nginx. Il faut rajouter la directive suivante au fichier de config nginx, en mettant le même chiffre que ce qu'on met dans le php.ini:
```
client_max_body_size 200M;
```
Désolé pour le bruit, ça servira toujours à ceux qui utilisent Nginx.

**Comment by broncowdd** [comment]
Ok, merci de l'info, ça servira sans doute ;-)

Le 14 février 2016 19:45:13 CET, Arno0x <notifications@github.com> a écrit :
>Non, ça n'est pas ça mais tu m'as mis sur la piste. Je n'ai même pas
>pensé à regarder les logs... En fait c'était une limitation au niveau
>de nginx. Il faut rajouter la directive suivante au fichier de config
>nginx, en mettant le même chiffre que ce qu'on met dans le php.ini:
>```
>client_max_body_size 200M;
>```
>Désolé pour le bruit, ça servira toujours à ceux qui utilisent Nginx.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/broncowdd/BoZoN/issues/86#issuecomment-183948755

-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.
