### ISSUE TITLE
un lien vers le github

### ISSUE THREAD

**Issue by cborne** [broncowdd/BoZoN#9]
On voit le blogueur mégalo qui met un lien vers son blog mais sur la page principale ce serait pas mal d'avoir un lien vers le projet github

**Comment by broncowdd** [comment]
Mouhouhaha ^^

**Comment by broncowdd** [comment]
Blogueur mégalo :'-D ça pourrait pas être plus éloigné de moi hahahah ! ^^
Par contre, la flemme de copier coller l'url du dépôt, carrément :-D
Je note quand même ;-)

**Comment by broncowdd** [comment]
#11 
Dans la version à venir
