### ISSUE TITLE
Folder contents not visible after adding jgg.

### ISSUE THREAD

**Issue by podbiker** [broncowdd/BoZoN#93]
Hi,

after adding a jpg to a folder the content of the folder is no longer visible in when browsing it via BoZoN.

The jpg is added correctly. This can be verified using the shell. The described behaviour occurs independent of the method by which the jpg is added.

Please look into this issue.

Thanks in advance,
PodBiker

**Comment by eauland** [comment]
You can use my fork and wait an issue.

But on my fork I don't resolve two functions (download folder zip and move a folder), actually I work on icons view.

Regards.

**Comment by eauland** [comment]
Hi,

You can use my fork and wait and issue.

Regards.

**Comment by broncowdd** [comment]
Very strange issue: could you describe how you proceed ? All works fine for me...

**Comment by fpp-gh** [comment]
I had the same issue at first, and it was due to "php5-GD" missing on the web server.
After I added it everything worked fine.
HTH,
fp
