### ISSUE TITLE
Parse error

### ISSUE THREAD

**Issue by ponkyw** [broncowdd/BoZoN#97]
Salut,
j'ai essayé une install fraîche suite à une erreur mais l'erreur persiste, à la place
de la liste des fichiers j'ai un :

`Parse error: syntax error, unexpected T_CONST in /drop/core/auto_thumb.php on line 2`

**Comment by broncowdd** [comment]
Je ferai un commit dans les prochains jours, en attendant, j'essaierai de regarder dans la journee.

Le 1 mars 2016 12:14:14 CET, ponkyw <notifications@github.com> a écrit :
>Salut,
>j'ai essayé une install fraîche suite à une erreur mais l'erreur
>persiste, à la place
>de la liste des fichiers j'ai un :
>
>`Parse error: syntax error, unexpected T_CONST in
>/drop/core/auto_thumb.php on line 2`
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/broncowdd/BoZoN/issues/97

-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.

**Comment by broncowdd** [comment]
Je n'ai pas cette erreur... as-tu récupéré la dernière version ?

**Comment by ponkyw** [comment]
Ouaip je viens de refaire un test, même erreur.

**Comment by broncowdd** [comment]
zarb...

**Comment by ponkyw** [comment]
Si tu as un mail perso je t'envoie l'adresse avec un compte de test.

**Comment by broncowdd** [comment]
yep, pas de souci: bronco AT warriordudimanche.net

**Comment by broncowdd** [comment]
tu peux y joindre le fichier auto_thumbs

**Comment by ponkyw** [comment]
Salut, j'ai toujours : 
` Parse error: syntax error, unexpected T_CONST in /droptest/core/auto_thumb.php on line 2`
 à la place de la liste des fichiers ...

**Comment by broncowdd** [comment]
zut... j'espérais que cette version résoudrait le problème... je vais regarder.

**Comment by broncowdd** [comment]
Essaie d'ajouter des retours chariots au début, juste après la balise <?php pour voir... (c'est con, mais j'ai déjà vu pire ^^)

**Comment by broncowdd** [comment]
Ou alors, toujours dans auto_thumbs, tu remplaces

```
const EXIF_ORIENTATION_TOP=1;
const EXIF_ORIENTATION_BOTTOM=3;
const EXIF_ORIENTATION_RIGHT=6;
const EXIF_ORIENTATION_LEFT=8;
```
par 
```
define('EXIF_ORIENTATION_TOP',1);
define('EXIF_ORIENTATION_BOTTOM',3);
define('EXIF_ORIENTATION_RIGHT',6);
define('EXIF_ORIENTATION_LEFT',8);

```

**Comment by ponkyw** [comment]
Salut,
les retours chariot n'ont rien fait mais ta dernière proposition fonctionne !!!
Merci !

**Comment by broncowdd** [comment]
cool ^^
